/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminService_GetAccountSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alert-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MonitorService_ListAlertRules"];
        put?: never;
        post: operations["MonitorService_CreateAlertRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alert-rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MonitorService_GetAlertRule"];
        put: operations["MonitorService_UpdateAlertRule"];
        post?: never;
        delete: operations["MonitorService_DeleteAlertRule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ========== 渠道管理（透传 channel-service）========== */
        get: operations["AdminService_ListChannels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RelayService_ChatCompletion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/configs/{namespace}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ConfigService_ListConfigs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/configs/{namespace}/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ConfigService_GetConfig"];
        put: operations["ConfigService_SetConfig"];
        post?: never;
        delete: operations["ConfigService_DeleteConfig"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health-checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MonitorService_ListHealthChecks"];
        put?: never;
        post: operations["MonitorService_SaveHealthCheck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health-checks/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MonitorService_GetLatestHealthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LogService_ListLogs"];
        put?: never;
        post: operations["LogService_IngestLog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/logs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LogService_GetLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/model-routings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ========== 模型路由 (P2 #3, 透传 channel-service) ========== */
        get: operations["AdminService_ListModelRoutings"];
        put?: never;
        post: operations["AdminService_UpsertModelRouting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/model-routings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["AdminService_DeleteModelRouting"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RelayService_ListModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["NotifyService_ListNotifications"];
        put?: never;
        post: operations["NotifyService_CreateNotification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notifications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["NotifyService_GetNotification"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notifications/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["NotifyService_UpdateNotificationStatus"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/redeem-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminService_ListRedeemCodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscription-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminService_ListSubscriptionAccounts"];
        put?: never;
        post: operations["AdminService_CreateSubscriptionAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscription-accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["AdminService_DeleteSubscriptionAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscription-accounts/{accountId}/reset-quota": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminService_ResetSubscriptionAccountQuota"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscription-accounts/{accountId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["AdminService_ChangeSubscriptionAccountStatus"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscription-accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["AdminService_UpdateSubscriptionAccount"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/system/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ========== 系统配置管理 ========== */
        get: operations["AdminService_GetSystemOptions"];
        put: operations["AdminService_UpdateSystemOptions"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ========== 用户管理（透传 identity-service）========== */
        get: operations["AdminService_ListUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "api.admin.v1.AdminAccountSnapshotResponse": {
            account?: components["schemas"]["api.common.v1.AccountInfo"];
        };
        "api.admin.v1.AdminChangeSubscriptionAccountStatusRequest": {
            accountId?: string;
            /** Format: int32 */
            status?: number;
        };
        "api.admin.v1.AdminChangeSubscriptionAccountStatusResponse": {
            success?: boolean;
            message?: string;
        };
        "api.admin.v1.AdminCreateSubscriptionAccountRequest": {
            name?: string;
            platform?: string;
            accountType?: string;
            group?: string;
            models?: string;
            priority?: string;
            baseUrl?: string;
            accessToken?: string;
            refreshToken?: string;
            expiresAt?: string;
            accountId?: string;
            fingerprint?: string;
            metadata?: string;
            /** Format: double */
            quotaLimitUsd?: number;
            /** Format: double */
            quotaUsedUsd?: number;
            /** Format: double */
            quotaDailyLimitUsd?: number;
            /** Format: double */
            quotaDailyUsedUsd?: number;
            quotaDailyWindowStart?: string;
            /** Format: double */
            quotaWeeklyLimitUsd?: number;
            /** Format: double */
            quotaWeeklyUsedUsd?: number;
            quotaWeeklyWindowStart?: string;
            /** Format: double */
            rateMultiplier?: number;
            /** Format: double */
            quota5hLimitUsd?: number;
            /** Format: double */
            quota5hUsedUsd?: number;
            quota5hWindowStart?: string;
            /** Format: int32 */
            rpmLimit?: number;
            /** Format: double */
            sessionWindowLimitUsd?: number;
            quotaResetStrategy?: string;
            quotaTimezone?: string;
            modelMapping?: string;
        };
        "api.admin.v1.AdminCreateSubscriptionAccountResponse": {
            success?: boolean;
            message?: string;
            accountId?: string;
        };
        "api.admin.v1.AdminDeleteSubscriptionAccountResponse": {
            success?: boolean;
            message?: string;
        };
        "api.admin.v1.AdminListChannelsResponse": {
            channels?: components["schemas"]["api.common.v1.ChannelSummary"][];
            total?: string;
        };
        "api.admin.v1.AdminListSubscriptionAccountsResponse": {
            accounts?: components["schemas"]["api.common.v1.SubscriptionAccountSummary"][];
            total?: string;
        };
        "api.admin.v1.AdminListUsersResponse": {
            users?: components["schemas"]["api.common.v1.UserInfo"][];
            total?: string;
        };
        "api.admin.v1.AdminResetSubscriptionAccountQuotaRequest": {
            accountId?: string;
            scope?: string;
        };
        "api.admin.v1.AdminResetSubscriptionAccountQuotaResponse": {
            success?: boolean;
            message?: string;
        };
        "api.admin.v1.AdminUpdateSubscriptionAccountRequest": {
            id?: string;
            name?: string;
            accountType?: string;
            group?: string;
            models?: string;
            priority?: string;
            baseUrl?: string;
            accessToken?: string;
            refreshToken?: string;
            expiresAt?: string;
            accountId?: string;
            fingerprint?: string;
            metadata?: string;
            /** Format: double */
            quotaLimitUsd?: number;
            /** Format: double */
            quotaUsedUsd?: number;
            /** Format: double */
            quotaDailyLimitUsd?: number;
            /** Format: double */
            quotaDailyUsedUsd?: number;
            quotaDailyWindowStart?: string;
            /** Format: double */
            quotaWeeklyLimitUsd?: number;
            /** Format: double */
            quotaWeeklyUsedUsd?: number;
            quotaWeeklyWindowStart?: string;
            /** Format: double */
            rateMultiplier?: number;
            /** Format: double */
            quota5hLimitUsd?: number;
            /** Format: double */
            quota5hUsedUsd?: number;
            quota5hWindowStart?: string;
            /** Format: int32 */
            rpmLimit?: number;
            /** Format: double */
            sessionWindowLimitUsd?: number;
            quotaResetStrategy?: string;
            quotaTimezone?: string;
            modelMapping?: string;
        };
        "api.admin.v1.AdminUpdateSubscriptionAccountResponse": {
            success?: boolean;
            message?: string;
        };
        "api.admin.v1.DeleteModelRoutingResponse": {
            success?: boolean;
            message?: string;
        };
        "api.admin.v1.GetSystemOptionsResponse": {
            options?: components["schemas"]["api.common.v1.SystemOptions"];
        };
        "api.admin.v1.ListLogsResponse": {
            logs?: components["schemas"]["api.admin.v1.LogEntry"][];
            total?: string;
        };
        "api.admin.v1.ListModelRoutingsResponse": {
            routings?: components["schemas"]["api.admin.v1.ModelRouting"][];
        };
        "api.admin.v1.ListRedeemCodesResponse": {
            codes?: components["schemas"]["api.admin.v1.RedeemCodeInfo"][];
            total?: string;
        };
        "api.admin.v1.LogEntry": {
            id?: string;
            userId?: string;
            type?: string;
            amount?: string;
            balanceAfter?: string;
            referenceId?: string;
            remark?: string;
            createdAt?: string;
        };
        "api.admin.v1.ModelRouting": {
            id?: string;
            groupName?: string;
            model?: string;
            platform?: string;
            subscriptionAccountId?: string;
            enabled?: boolean;
            /** Format: int32 */
            priority?: number;
            createdAt?: string;
            updatedAt?: string;
        };
        "api.admin.v1.RedeemCodeInfo": {
            code?: string;
            name?: string;
            amount?: string;
            /** Format: int32 */
            count?: number;
            /** Format: int32 */
            status?: number;
            createdBy?: string;
            createdAt?: string;
        };
        "api.admin.v1.UpdateSystemOptionsRequest": {
            options?: components["schemas"]["api.common.v1.SystemOptions"];
        };
        "api.admin.v1.UpdateSystemOptionsResponse": {
            success?: boolean;
            message?: string;
        };
        "api.admin.v1.UpsertModelRoutingRequest": {
            groupName?: string;
            model?: string;
            platform?: string;
            subscriptionAccountId?: string;
            enabled?: boolean;
            /** Format: int32 */
            priority?: number;
        };
        "api.admin.v1.UpsertModelRoutingResponse": {
            success?: boolean;
            message?: string;
            id?: string;
        };
        "api.common.v1.AccountInfo": {
            userId?: string;
            username?: string;
            displayName?: string;
            group?: string;
            balance?: string;
            usedAmount?: string;
            requestCount?: string;
            frozenAmount?: string;
            /** Format: int32 */
            status?: number;
        };
        "api.common.v1.ChannelSummary": {
            id?: string;
            name?: string;
            /** Format: int32 */
            type?: number;
            group?: string;
            /** Format: int32 */
            status?: number;
            priority?: string;
            createdAt?: string;
            models?: string;
            /** Format: uint32 */
            weight?: number;
            testTime?: string;
            responseTime?: string;
            /** Format: double */
            balance?: number;
            balanceUpdatedTime?: string;
            usedQuota?: string;
            healthStatus?: string;
            healthLastError?: string;
            healthLastSuccessTime?: string;
            healthLastFailureTime?: string;
            /** Format: int32 */
            healthConsecutiveFailures?: number;
            circuitOpenedUntil?: string;
            restrictModels?: boolean;
        };
        "api.common.v1.SubscriptionAccountSummary": {
            id?: string;
            name?: string;
            platform?: string;
            accountType?: string;
            /** Format: int32 */
            status?: number;
            group?: string;
            models?: string;
            priority?: string;
            accountId?: string;
            expiresAt?: string;
            updatedAt?: string;
            lastUsedAt?: string;
            rateLimitedUntil?: string;
            /** Format: float */
            quotaUsedPercent?: number;
            quotaResetAt?: string;
            /** Format: int32 */
            concurrency?: number;
            /** Format: double */
            primaryQuotaUsedPercent?: number;
            /** Format: int32 */
            primaryQuotaResetAfterSeconds?: number;
            /** Format: int32 */
            primaryQuotaWindowMinutes?: number;
            /** Format: double */
            secondaryQuotaUsedPercent?: number;
            /** Format: int32 */
            secondaryQuotaResetAfterSeconds?: number;
            /** Format: int32 */
            secondaryQuotaWindowMinutes?: number;
            /** Format: double */
            primaryOverSecondaryPercent?: number;
            quotaSnapshotUpdatedAt?: string;
            quotaSnapshotPaused?: boolean;
            /** Format: double */
            quotaLimitUsd?: number;
            /** Format: double */
            quotaUsedUsd?: number;
            /** Format: double */
            quotaDailyLimitUsd?: number;
            /** Format: double */
            quotaDailyUsedUsd?: number;
            quotaDailyWindowStart?: string;
            /** Format: double */
            quotaWeeklyLimitUsd?: number;
            /** Format: double */
            quotaWeeklyUsedUsd?: number;
            quotaWeeklyWindowStart?: string;
            /** Format: double */
            rateMultiplier?: number;
            /** Format: double */
            quota5hLimitUsd?: number;
            /** Format: double */
            quota5hUsedUsd?: number;
            quota5hWindowStart?: string;
            /** Format: int32 */
            rpmLimit?: number;
            /** Format: double */
            sessionWindowLimitUsd?: number;
            quotaResetStrategy?: string;
            quotaTimezone?: string;
            unschedulableReason?: string;
            recoveryPolicy?: string;
            expectedRecoveryAt?: string;
            unschedulableSince?: string;
            modelMapping?: string;
            /** Format: int32 */
            weight?: number;
        };
        "api.common.v1.SystemOptions": {
            siteTitle?: string;
            siteDescription?: string;
            registrationEnabled?: boolean;
            chatHistoryEnabled?: boolean;
            theme?: string;
            notice?: string;
            maxTokenPerUser?: string;
            /** Format: double */
            defaultRatio?: number;
        };
        "api.common.v1.UserInfo": {
            id?: string;
            username?: string;
            displayName?: string;
            email?: string;
            group?: string;
            /** Format: int32 */
            status?: number;
            balance?: string;
            usedAmount?: string;
            frozenAmount?: string;
            createdAt?: string;
            lastLoginAt?: string;
            /**
             * Format: int32
             * @description 0=guest, 1=common, 10=admin, 100=root. See biz.Role* constants.
             */
            role?: number;
        };
        "api.config.v1.DeleteConfigResponse": {
            success?: boolean;
        };
        "api.config.v1.GetConfigResponse": {
            id?: string;
            namespace?: string;
            key?: string;
            value?: string;
            comment?: string;
            updatedAt?: string;
        };
        "api.config.v1.ListConfigsResponse": {
            items?: components["schemas"]["api.config.v1.GetConfigResponse"][];
            total?: string;
        };
        "api.config.v1.SetConfigRequest": {
            namespace?: string;
            key?: string;
            value?: string;
            comment?: string;
        };
        "api.config.v1.SetConfigResponse": {
            success?: boolean;
        };
        "api.log.v1.GetLogResponse": {
            id?: string;
            level?: string;
            message?: string;
            source?: string;
            requestId?: string;
            userId?: string;
            createdAt?: string;
            username?: string;
            tokenName?: string;
            modelName?: string;
            quota?: string;
            promptTokens?: string;
            completionTokens?: string;
            channelId?: string;
            elapsedTime?: string;
            isStream?: boolean;
            cacheReadTokens?: string;
            subscriptionAccountId?: string;
            /** @description v0.11.0 cache-creation buckets (docs/design/token-usage-semantics.md). */
            cacheCreation5mTokens?: string;
            cacheCreation1hTokens?: string;
            /**
             * @description token-usage-billing-semantics-remediation (2026-08-31) §9.1 display
             *      contract. quota keeps its legacy reported-total meaning; new consumers
             *      must prefer billable_total_tokens and MUST NOT re-derive totals via
             *      prompt-cache+output+cache. usage_parse_status='legacy' rows have unknown
             *      historical semantics and must be displayed as such.
             */
            uncachedInputTokens?: string;
            reportedPromptTokens?: string;
            reportedTotalTokens?: string;
            billableTotalTokens?: string;
            usageSemantics?: string;
            usageProtocol?: string;
            usageParseStatus?: string;
            /** Format: int32 */
            usageContractVersion?: number;
            usageDecisionReason?: string;
        };
        "api.log.v1.IngestLogRequest": {
            level?: string;
            message?: string;
            source?: string;
            requestId?: string;
            userId?: string;
            username?: string;
            tokenName?: string;
            modelName?: string;
            quota?: string;
            promptTokens?: string;
            completionTokens?: string;
            channelId?: string;
            elapsedTime?: string;
            isStream?: boolean;
            cacheReadTokens?: string;
            subscriptionAccountId?: string;
            /** @description v0.11.0 cache-creation buckets (docs/design/token-usage-semantics.md). */
            cacheCreation5mTokens?: string;
            cacheCreation1hTokens?: string;
            /** @description Stable producer key. Retries with the same key return the original row. */
            dedupeKey?: string;
            /**
             * @description token-usage-billing-semantics-remediation (2026-08-31) §6.2/§9.1.
             *      quota keeps its legacy reported-total meaning; the fields below carry the
             *      canonical display contract. Legacy producers (usage_contract_version=0)
             *      leave them at zero value and the row is stored with
             *      usage_parse_status='legacy'.
             */
            uncachedInputTokens?: string;
            reportedPromptTokens?: string;
            reportedTotalTokens?: string;
            billableTotalTokens?: string;
            usageSemantics?: string;
            usageProtocol?: string;
            usageFieldShape?: string;
            usageParseStatus?: string;
            /** Format: int32 */
            usageContractVersion?: number;
            canonicalPresent?: boolean;
            usageDecisionReason?: string;
        };
        "api.log.v1.IngestLogResponse": {
            id?: string;
        };
        "api.log.v1.ListLogsResponse": {
            items?: components["schemas"]["api.log.v1.GetLogResponse"][];
            total?: string;
        };
        "api.monitor.v1.AlertRuleItem": {
            id?: string;
            name?: string;
            serviceName?: string;
            metric?: string;
            /** Format: double */
            threshold?: number;
            operator?: string;
            /** Format: int32 */
            duration?: number;
            enabled?: boolean;
            createdAt?: string;
        };
        "api.monitor.v1.CreateAlertRuleRequest": {
            name?: string;
            serviceName?: string;
            metric?: string;
            /** Format: double */
            threshold?: number;
            operator?: string;
            /** Format: int32 */
            duration?: number;
            enabled?: boolean;
        };
        "api.monitor.v1.CreateAlertRuleResponse": {
            rule?: components["schemas"]["api.monitor.v1.AlertRuleItem"];
        };
        "api.monitor.v1.DeleteAlertRuleResponse": {
            success?: boolean;
        };
        "api.monitor.v1.GetAlertRuleResponse": {
            rule?: components["schemas"]["api.monitor.v1.AlertRuleItem"];
        };
        "api.monitor.v1.GetLatestHealthCheckResponse": {
            check?: components["schemas"]["api.monitor.v1.HealthCheckItem"];
        };
        "api.monitor.v1.HealthCheckItem": {
            id?: string;
            serviceName?: string;
            status?: string;
            responseTime?: string;
            checkedAt?: string;
        };
        "api.monitor.v1.ListAlertRulesResponse": {
            items?: components["schemas"]["api.monitor.v1.AlertRuleItem"][];
            total?: string;
        };
        "api.monitor.v1.ListHealthChecksResponse": {
            items?: components["schemas"]["api.monitor.v1.HealthCheckItem"][];
            total?: string;
        };
        "api.monitor.v1.SaveHealthCheckRequest": {
            serviceName?: string;
            status?: string;
            responseTime?: string;
        };
        "api.monitor.v1.SaveHealthCheckResponse": {
            success?: boolean;
        };
        "api.monitor.v1.UpdateAlertRuleRequest": {
            id?: string;
            name?: string;
            serviceName?: string;
            metric?: string;
            /** Format: double */
            threshold?: number;
            operator?: string;
            /** Format: int32 */
            duration?: number;
            enabled?: boolean;
        };
        "api.monitor.v1.UpdateAlertRuleResponse": {
            success?: boolean;
        };
        "api.notify.v1.CreateNotificationRequest": {
            type?: string;
            recipient?: string;
            subject?: string;
            content?: string;
        };
        "api.notify.v1.CreateNotificationResponse": {
            notification?: components["schemas"]["api.notify.v1.NotificationItem"];
        };
        "api.notify.v1.GetNotificationResponse": {
            notification?: components["schemas"]["api.notify.v1.NotificationItem"];
        };
        "api.notify.v1.ListNotificationsResponse": {
            items?: components["schemas"]["api.notify.v1.NotificationItem"][];
            total?: string;
        };
        "api.notify.v1.NotificationItem": {
            id?: string;
            type?: string;
            recipient?: string;
            subject?: string;
            content?: string;
            status?: string;
            /** Format: int32 */
            retryCount?: number;
            createdAt?: string;
            sentAt?: string;
            lastError?: string;
        };
        "api.notify.v1.UpdateNotificationStatusRequest": {
            id?: string;
            status?: string;
        };
        "api.notify.v1.UpdateNotificationStatusResponse": {
            success?: boolean;
        };
        "api.relay.v1.ChatCompletionRequest": {
            model?: string;
            messages?: components["schemas"]["api.relay.v1.Message"][];
            stream?: boolean;
            /** Format: double */
            temperature?: number;
            /** Format: int32 */
            maxTokens?: number;
        };
        "api.relay.v1.ChatCompletionResponse": {
            id?: string;
            object?: string;
            created?: string;
            model?: string;
            choices?: components["schemas"]["api.relay.v1.Choice"][];
            usage?: components["schemas"]["api.relay.v1.Usage"];
        };
        "api.relay.v1.Choice": {
            /** Format: int32 */
            index?: number;
            message?: components["schemas"]["api.relay.v1.Message"];
            finishReason?: string;
        };
        "api.relay.v1.ListModelsResponse": {
            models?: components["schemas"]["api.relay.v1.ModelInfo"][];
        };
        "api.relay.v1.Message": {
            role?: string;
            content?: string;
        };
        "api.relay.v1.ModelInfo": {
            id?: string;
            object?: string;
            created?: string;
            ownedBy?: string;
        };
        "api.relay.v1.Usage": {
            /** Format: int32 */
            promptTokens?: number;
            /** Format: int32 */
            completionTokens?: number;
            /** Format: int32 */
            totalTokens?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AdminService_GetAccountSnapshot: {
        parameters: {
            query?: {
                userId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.admin.v1.AdminAccountSnapshotResponse"];
                };
            };
        };
    };
    MonitorService_ListAlertRules: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.monitor.v1.ListAlertRulesResponse"];
                };
            };
        };
    };
    MonitorService_CreateAlertRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["api.monitor.v1.CreateAlertRuleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.monitor.v1.CreateAlertRuleResponse"];
                };
            };
        };
    };
    MonitorService_GetAlertRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.monitor.v1.GetAlertRuleResponse"];
                };
            };
        };
    };
    MonitorService_UpdateAlertRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["api.monitor.v1.UpdateAlertRuleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.monitor.v1.UpdateAlertRuleResponse"];
                };
            };
        };
    };
    MonitorService_DeleteAlertRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.monitor.v1.DeleteAlertRuleResponse"];
                };
            };
        };
    };
    AdminService_ListChannels: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                keyword?: string;
                group?: string;
                status?: number;
                type?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.admin.v1.AdminListChannelsResponse"];
                };
            };
        };
    };
    RelayService_ChatCompletion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["api.relay.v1.ChatCompletionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.relay.v1.ChatCompletionResponse"];
                };
            };
        };
    };
    ConfigService_ListConfigs: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path: {
                namespace: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.config.v1.ListConfigsResponse"];
                };
            };
        };
    };
    ConfigService_GetConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.config.v1.GetConfigResponse"];
                };
            };
        };
    };
    ConfigService_SetConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["api.config.v1.SetConfigRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.config.v1.SetConfigResponse"];
                };
            };
        };
    };
    ConfigService_DeleteConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.config.v1.DeleteConfigResponse"];
                };
            };
        };
    };
    MonitorService_ListHealthChecks: {
        parameters: {
            query?: {
                serviceName?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.monitor.v1.ListHealthChecksResponse"];
                };
            };
        };
    };
    MonitorService_SaveHealthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["api.monitor.v1.SaveHealthCheckRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.monitor.v1.SaveHealthCheckResponse"];
                };
            };
        };
    };
    MonitorService_GetLatestHealthCheck: {
        parameters: {
            query?: {
                serviceName?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.monitor.v1.GetLatestHealthCheckResponse"];
                };
            };
        };
    };
    LogService_ListLogs: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.log.v1.ListLogsResponse"];
                };
            };
        };
    };
    LogService_IngestLog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["api.log.v1.IngestLogRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.log.v1.IngestLogResponse"];
                };
            };
        };
    };
    LogService_GetLog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.log.v1.GetLogResponse"];
                };
            };
        };
    };
    AdminService_ListModelRoutings: {
        parameters: {
            query?: {
                groupName?: string;
                model?: string;
                platform?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.admin.v1.ListModelRoutingsResponse"];
                };
            };
        };
    };
    AdminService_UpsertModelRouting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["api.admin.v1.UpsertModelRoutingRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.admin.v1.UpsertModelRoutingResponse"];
                };
            };
        };
    };
    AdminService_DeleteModelRouting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.admin.v1.DeleteModelRoutingResponse"];
                };
            };
        };
    };
    RelayService_ListModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.relay.v1.ListModelsResponse"];
                };
            };
        };
    };
    NotifyService_ListNotifications: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                type?: string;
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.notify.v1.ListNotificationsResponse"];
                };
            };
        };
    };
    NotifyService_CreateNotification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["api.notify.v1.CreateNotificationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.notify.v1.CreateNotificationResponse"];
                };
            };
        };
    };
    NotifyService_GetNotification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.notify.v1.GetNotificationResponse"];
                };
            };
        };
    };
    NotifyService_UpdateNotificationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["api.notify.v1.UpdateNotificationStatusRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.notify.v1.UpdateNotificationStatusResponse"];
                };
            };
        };
    };
    AdminService_ListRedeemCodes: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.admin.v1.ListRedeemCodesResponse"];
                };
            };
        };
    };
    AdminService_ListSubscriptionAccounts: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                keyword?: string;
                group?: string;
                status?: number;
                platform?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.admin.v1.AdminListSubscriptionAccountsResponse"];
                };
            };
        };
    };
    AdminService_CreateSubscriptionAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["api.admin.v1.AdminCreateSubscriptionAccountRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.admin.v1.AdminCreateSubscriptionAccountResponse"];
                };
            };
        };
    };
    AdminService_DeleteSubscriptionAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.admin.v1.AdminDeleteSubscriptionAccountResponse"];
                };
            };
        };
    };
    AdminService_ResetSubscriptionAccountQuota: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["api.admin.v1.AdminResetSubscriptionAccountQuotaRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.admin.v1.AdminResetSubscriptionAccountQuotaResponse"];
                };
            };
        };
    };
    AdminService_ChangeSubscriptionAccountStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["api.admin.v1.AdminChangeSubscriptionAccountStatusRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.admin.v1.AdminChangeSubscriptionAccountStatusResponse"];
                };
            };
        };
    };
    AdminService_UpdateSubscriptionAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["api.admin.v1.AdminUpdateSubscriptionAccountRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.admin.v1.AdminUpdateSubscriptionAccountResponse"];
                };
            };
        };
    };
    AdminService_GetSystemOptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.admin.v1.GetSystemOptionsResponse"];
                };
            };
        };
    };
    AdminService_UpdateSystemOptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["api.admin.v1.UpdateSystemOptionsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.admin.v1.UpdateSystemOptionsResponse"];
                };
            };
        };
    };
    AdminService_ListUsers: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                keyword?: string;
                group?: string;
                status?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api.admin.v1.AdminListUsersResponse"];
                };
            };
        };
    };
}
