// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.1
// source: api/relay/v1/relay.proto

package relayv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationRelayServiceChatCompletion = "/api.relay.v1.RelayService/ChatCompletion"
const OperationRelayServiceListModels = "/api.relay.v1.RelayService/ListModels"

type RelayServiceHTTPServer interface {
	ChatCompletion(context.Context, *ChatCompletionRequest) (*ChatCompletionResponse, error)
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
}

func RegisterRelayServiceHTTPServer(s *http.Server, srv RelayServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/chat/completions", _RelayService_ChatCompletion0_HTTP_Handler(srv))
	r.GET("/v1/models", _RelayService_ListModels0_HTTP_Handler(srv))
}

func _RelayService_ChatCompletion0_HTTP_Handler(srv RelayServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ChatCompletionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRelayServiceChatCompletion)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ChatCompletion(ctx, req.(*ChatCompletionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ChatCompletionResponse)
		return ctx.Result(200, reply)
	}
}

func _RelayService_ListModels0_HTTP_Handler(srv RelayServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListModelsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRelayServiceListModels)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListModels(ctx, req.(*ListModelsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListModelsResponse)
		return ctx.Result(200, reply)
	}
}

type RelayServiceHTTPClient interface {
	ChatCompletion(ctx context.Context, req *ChatCompletionRequest, opts ...http.CallOption) (rsp *ChatCompletionResponse, err error)
	ListModels(ctx context.Context, req *ListModelsRequest, opts ...http.CallOption) (rsp *ListModelsResponse, err error)
}

type RelayServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewRelayServiceHTTPClient(client *http.Client) RelayServiceHTTPClient {
	return &RelayServiceHTTPClientImpl{client}
}

func (c *RelayServiceHTTPClientImpl) ChatCompletion(ctx context.Context, in *ChatCompletionRequest, opts ...http.CallOption) (*ChatCompletionResponse, error) {
	var out ChatCompletionResponse
	pattern := "/v1/chat/completions"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRelayServiceChatCompletion))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *RelayServiceHTTPClientImpl) ListModels(ctx context.Context, in *ListModelsRequest, opts ...http.CallOption) (*ListModelsResponse, error) {
	var out ListModelsResponse
	pattern := "/v1/models"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRelayServiceListModels))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
