// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/monitor/v1/monitor.proto

package monitorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveHealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ResponseTime  int64                  `protobuf:"varint,3,opt,name=response_time,json=responseTime,proto3" json:"response_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveHealthCheckRequest) Reset() {
	*x = SaveHealthCheckRequest{}
	mi := &file_api_monitor_v1_monitor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveHealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveHealthCheckRequest) ProtoMessage() {}

func (x *SaveHealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_monitor_v1_monitor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveHealthCheckRequest.ProtoReflect.Descriptor instead.
func (*SaveHealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_monitor_v1_monitor_proto_rawDescGZIP(), []int{0}
}

func (x *SaveHealthCheckRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *SaveHealthCheckRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SaveHealthCheckRequest) GetResponseTime() int64 {
	if x != nil {
		return x.ResponseTime
	}
	return 0
}

type SaveHealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveHealthCheckResponse) Reset() {
	*x = SaveHealthCheckResponse{}
	mi := &file_api_monitor_v1_monitor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveHealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveHealthCheckResponse) ProtoMessage() {}

func (x *SaveHealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_monitor_v1_monitor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveHealthCheckResponse.ProtoReflect.Descriptor instead.
func (*SaveHealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_monitor_v1_monitor_proto_rawDescGZIP(), []int{1}
}

func (x *SaveHealthCheckResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListHealthChecksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHealthChecksRequest) Reset() {
	*x = ListHealthChecksRequest{}
	mi := &file_api_monitor_v1_monitor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHealthChecksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHealthChecksRequest) ProtoMessage() {}

func (x *ListHealthChecksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_monitor_v1_monitor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHealthChecksRequest.ProtoReflect.Descriptor instead.
func (*ListHealthChecksRequest) Descriptor() ([]byte, []int) {
	return file_api_monitor_v1_monitor_proto_rawDescGZIP(), []int{2}
}

func (x *ListHealthChecksRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ListHealthChecksRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListHealthChecksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type HealthCheckItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ResponseTime  int64                  `protobuf:"varint,4,opt,name=response_time,json=responseTime,proto3" json:"response_time,omitempty"`
	CheckedAt     int64                  `protobuf:"varint,5,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckItem) Reset() {
	*x = HealthCheckItem{}
	mi := &file_api_monitor_v1_monitor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckItem) ProtoMessage() {}

func (x *HealthCheckItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_monitor_v1_monitor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckItem.ProtoReflect.Descriptor instead.
func (*HealthCheckItem) Descriptor() ([]byte, []int) {
	return file_api_monitor_v1_monitor_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HealthCheckItem) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *HealthCheckItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckItem) GetResponseTime() int64 {
	if x != nil {
		return x.ResponseTime
	}
	return 0
}

func (x *HealthCheckItem) GetCheckedAt() int64 {
	if x != nil {
		return x.CheckedAt
	}
	return 0
}

type ListHealthChecksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*HealthCheckItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHealthChecksResponse) Reset() {
	*x = ListHealthChecksResponse{}
	mi := &file_api_monitor_v1_monitor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHealthChecksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHealthChecksResponse) ProtoMessage() {}

func (x *ListHealthChecksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_monitor_v1_monitor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHealthChecksResponse.ProtoReflect.Descriptor instead.
func (*ListHealthChecksResponse) Descriptor() ([]byte, []int) {
	return file_api_monitor_v1_monitor_proto_rawDescGZIP(), []int{4}
}

func (x *ListHealthChecksResponse) GetItems() []*HealthCheckItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListHealthChecksResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetLatestHealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestHealthCheckRequest) Reset() {
	*x = GetLatestHealthCheckRequest{}
	mi := &file_api_monitor_v1_monitor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestHealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestHealthCheckRequest) ProtoMessage() {}

func (x *GetLatestHealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_monitor_v1_monitor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestHealthCheckRequest.ProtoReflect.Descriptor instead.
func (*GetLatestHealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_monitor_v1_monitor_proto_rawDescGZIP(), []int{5}
}

func (x *GetLatestHealthCheckRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type GetLatestHealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Check         *HealthCheckItem       `protobuf:"bytes,1,opt,name=check,proto3" json:"check,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestHealthCheckResponse) Reset() {
	*x = GetLatestHealthCheckResponse{}
	mi := &file_api_monitor_v1_monitor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestHealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestHealthCheckResponse) ProtoMessage() {}

func (x *GetLatestHealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_monitor_v1_monitor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestHealthCheckResponse.ProtoReflect.Descriptor instead.
func (*GetLatestHealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_monitor_v1_monitor_proto_rawDescGZIP(), []int{6}
}

func (x *GetLatestHealthCheckResponse) GetCheck() *HealthCheckItem {
	if x != nil {
		return x.Check
	}
	return nil
}

type CreateAlertRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Metric        string                 `protobuf:"bytes,3,opt,name=metric,proto3" json:"metric,omitempty"`
	Threshold     float64                `protobuf:"fixed64,4,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Operator      string                 `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Duration      int32                  `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`
	Enabled       bool                   `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlertRuleRequest) Reset() {
	*x = CreateAlertRuleRequest{}
	mi := &file_api_monitor_v1_monitor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlertRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlertRuleRequest) ProtoMessage() {}

func (x *CreateAlertRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_monitor_v1_monitor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlertRuleRequest.ProtoReflect.Descriptor instead.
func (*CreateAlertRuleRequest) Descriptor() ([]byte, []int) {
	return file_api_monitor_v1_monitor_proto_rawDescGZIP(), []int{7}
}

func (x *CreateAlertRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAlertRuleRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *CreateAlertRuleRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *CreateAlertRuleRequest) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *CreateAlertRuleRequest) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *CreateAlertRuleRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *CreateAlertRuleRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type AlertRuleItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Metric        string                 `protobuf:"bytes,4,opt,name=metric,proto3" json:"metric,omitempty"`
	Threshold     float64                `protobuf:"fixed64,5,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Operator      string                 `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`
	Duration      int32                  `protobuf:"varint,7,opt,name=duration,proto3" json:"duration,omitempty"`
	Enabled       bool                   `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertRuleItem) Reset() {
	*x = AlertRuleItem{}
	mi := &file_api_monitor_v1_monitor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertRuleItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertRuleItem) ProtoMessage() {}

func (x *AlertRuleItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_monitor_v1_monitor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertRuleItem.ProtoReflect.Descriptor instead.
func (*AlertRuleItem) Descriptor() ([]byte, []int) {
	return file_api_monitor_v1_monitor_proto_rawDescGZIP(), []int{8}
}

func (x *AlertRuleItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AlertRuleItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AlertRuleItem) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *AlertRuleItem) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *AlertRuleItem) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *AlertRuleItem) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *AlertRuleItem) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *AlertRuleItem) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AlertRuleItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type CreateAlertRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *AlertRuleItem         `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlertRuleResponse) Reset() {
	*x = CreateAlertRuleResponse{}
	mi := &file_api_monitor_v1_monitor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlertRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlertRuleResponse) ProtoMessage() {}

func (x *CreateAlertRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_monitor_v1_monitor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlertRuleResponse.ProtoReflect.Descriptor instead.
func (*CreateAlertRuleResponse) Descriptor() ([]byte, []int) {
	return file_api_monitor_v1_monitor_proto_rawDescGZIP(), []int{9}
}

func (x *CreateAlertRuleResponse) GetRule() *AlertRuleItem {
	if x != nil {
		return x.Rule
	}
	return nil
}

type ListAlertRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertRulesRequest) Reset() {
	*x = ListAlertRulesRequest{}
	mi := &file_api_monitor_v1_monitor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertRulesRequest) ProtoMessage() {}

func (x *ListAlertRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_monitor_v1_monitor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertRulesRequest.ProtoReflect.Descriptor instead.
func (*ListAlertRulesRequest) Descriptor() ([]byte, []int) {
	return file_api_monitor_v1_monitor_proto_rawDescGZIP(), []int{10}
}

func (x *ListAlertRulesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAlertRulesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListAlertRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AlertRuleItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertRulesResponse) Reset() {
	*x = ListAlertRulesResponse{}
	mi := &file_api_monitor_v1_monitor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertRulesResponse) ProtoMessage() {}

func (x *ListAlertRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_monitor_v1_monitor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertRulesResponse.ProtoReflect.Descriptor instead.
func (*ListAlertRulesResponse) Descriptor() ([]byte, []int) {
	return file_api_monitor_v1_monitor_proto_rawDescGZIP(), []int{11}
}

func (x *ListAlertRulesResponse) GetItems() []*AlertRuleItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListAlertRulesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_api_monitor_v1_monitor_proto protoreflect.FileDescriptor

const file_api_monitor_v1_monitor_proto_rawDesc = "" +
	"\n" +
	"\x1capi/monitor/v1/monitor.proto\x12\x0eapi.monitor.v1\"x\n" +
	"\x16SaveHealthCheckRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rresponse_time\x18\x03 \x01(\x03R\fresponseTime\"3\n" +
	"\x17SaveHealthCheckResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"m\n" +
	"\x17ListHealthChecksRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xa0\x01\n" +
	"\x0fHealthCheckItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\rresponse_time\x18\x04 \x01(\x03R\fresponseTime\x12\x1d\n" +
	"\n" +
	"checked_at\x18\x05 \x01(\x03R\tcheckedAt\"g\n" +
	"\x18ListHealthChecksResponse\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.api.monitor.v1.HealthCheckItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"@\n" +
	"\x1bGetLatestHealthCheckRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"U\n" +
	"\x1cGetLatestHealthCheckResponse\x125\n" +
	"\x05check\x18\x01 \x01(\v2\x1f.api.monitor.v1.HealthCheckItemR\x05check\"\xd7\x01\n" +
	"\x16CreateAlertRuleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x16\n" +
	"\x06metric\x18\x03 \x01(\tR\x06metric\x12\x1c\n" +
	"\tthreshold\x18\x04 \x01(\x01R\tthreshold\x12\x1a\n" +
	"\boperator\x18\x05 \x01(\tR\boperator\x12\x1a\n" +
	"\bduration\x18\x06 \x01(\x05R\bduration\x12\x18\n" +
	"\aenabled\x18\a \x01(\bR\aenabled\"\xfd\x01\n" +
	"\rAlertRuleItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12\x16\n" +
	"\x06metric\x18\x04 \x01(\tR\x06metric\x12\x1c\n" +
	"\tthreshold\x18\x05 \x01(\x01R\tthreshold\x12\x1a\n" +
	"\boperator\x18\x06 \x01(\tR\boperator\x12\x1a\n" +
	"\bduration\x18\a \x01(\x05R\bduration\x12\x18\n" +
	"\aenabled\x18\b \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\"L\n" +
	"\x17CreateAlertRuleResponse\x121\n" +
	"\x04rule\x18\x01 \x01(\v2\x1d.api.monitor.v1.AlertRuleItemR\x04rule\"H\n" +
	"\x15ListAlertRulesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"c\n" +
	"\x16ListAlertRulesResponse\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.api.monitor.v1.AlertRuleItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\x93\x04\n" +
	"\x0eMonitorService\x12b\n" +
	"\x0fSaveHealthCheck\x12&.api.monitor.v1.SaveHealthCheckRequest\x1a'.api.monitor.v1.SaveHealthCheckResponse\x12e\n" +
	"\x10ListHealthChecks\x12'.api.monitor.v1.ListHealthChecksRequest\x1a(.api.monitor.v1.ListHealthChecksResponse\x12q\n" +
	"\x14GetLatestHealthCheck\x12+.api.monitor.v1.GetLatestHealthCheckRequest\x1a,.api.monitor.v1.GetLatestHealthCheckResponse\x12b\n" +
	"\x0fCreateAlertRule\x12&.api.monitor.v1.CreateAlertRuleRequest\x1a'.api.monitor.v1.CreateAlertRuleResponse\x12_\n" +
	"\x0eListAlertRules\x12%.api.monitor.v1.ListAlertRulesRequest\x1a&.api.monitor.v1.ListAlertRulesResponseB(Z&micro-one-api/api/monitor/v1;monitorv1b\x06proto3"

var (
	file_api_monitor_v1_monitor_proto_rawDescOnce sync.Once
	file_api_monitor_v1_monitor_proto_rawDescData []byte
)

func file_api_monitor_v1_monitor_proto_rawDescGZIP() []byte {
	file_api_monitor_v1_monitor_proto_rawDescOnce.Do(func() {
		file_api_monitor_v1_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_monitor_v1_monitor_proto_rawDesc), len(file_api_monitor_v1_monitor_proto_rawDesc)))
	})
	return file_api_monitor_v1_monitor_proto_rawDescData
}

var file_api_monitor_v1_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_monitor_v1_monitor_proto_goTypes = []any{
	(*SaveHealthCheckRequest)(nil),       // 0: api.monitor.v1.SaveHealthCheckRequest
	(*SaveHealthCheckResponse)(nil),      // 1: api.monitor.v1.SaveHealthCheckResponse
	(*ListHealthChecksRequest)(nil),      // 2: api.monitor.v1.ListHealthChecksRequest
	(*HealthCheckItem)(nil),              // 3: api.monitor.v1.HealthCheckItem
	(*ListHealthChecksResponse)(nil),     // 4: api.monitor.v1.ListHealthChecksResponse
	(*GetLatestHealthCheckRequest)(nil),  // 5: api.monitor.v1.GetLatestHealthCheckRequest
	(*GetLatestHealthCheckResponse)(nil), // 6: api.monitor.v1.GetLatestHealthCheckResponse
	(*CreateAlertRuleRequest)(nil),       // 7: api.monitor.v1.CreateAlertRuleRequest
	(*AlertRuleItem)(nil),                // 8: api.monitor.v1.AlertRuleItem
	(*CreateAlertRuleResponse)(nil),      // 9: api.monitor.v1.CreateAlertRuleResponse
	(*ListAlertRulesRequest)(nil),        // 10: api.monitor.v1.ListAlertRulesRequest
	(*ListAlertRulesResponse)(nil),       // 11: api.monitor.v1.ListAlertRulesResponse
}
var file_api_monitor_v1_monitor_proto_depIdxs = []int32{
	3,  // 0: api.monitor.v1.ListHealthChecksResponse.items:type_name -> api.monitor.v1.HealthCheckItem
	3,  // 1: api.monitor.v1.GetLatestHealthCheckResponse.check:type_name -> api.monitor.v1.HealthCheckItem
	8,  // 2: api.monitor.v1.CreateAlertRuleResponse.rule:type_name -> api.monitor.v1.AlertRuleItem
	8,  // 3: api.monitor.v1.ListAlertRulesResponse.items:type_name -> api.monitor.v1.AlertRuleItem
	0,  // 4: api.monitor.v1.MonitorService.SaveHealthCheck:input_type -> api.monitor.v1.SaveHealthCheckRequest
	2,  // 5: api.monitor.v1.MonitorService.ListHealthChecks:input_type -> api.monitor.v1.ListHealthChecksRequest
	5,  // 6: api.monitor.v1.MonitorService.GetLatestHealthCheck:input_type -> api.monitor.v1.GetLatestHealthCheckRequest
	7,  // 7: api.monitor.v1.MonitorService.CreateAlertRule:input_type -> api.monitor.v1.CreateAlertRuleRequest
	10, // 8: api.monitor.v1.MonitorService.ListAlertRules:input_type -> api.monitor.v1.ListAlertRulesRequest
	1,  // 9: api.monitor.v1.MonitorService.SaveHealthCheck:output_type -> api.monitor.v1.SaveHealthCheckResponse
	4,  // 10: api.monitor.v1.MonitorService.ListHealthChecks:output_type -> api.monitor.v1.ListHealthChecksResponse
	6,  // 11: api.monitor.v1.MonitorService.GetLatestHealthCheck:output_type -> api.monitor.v1.GetLatestHealthCheckResponse
	9,  // 12: api.monitor.v1.MonitorService.CreateAlertRule:output_type -> api.monitor.v1.CreateAlertRuleResponse
	11, // 13: api.monitor.v1.MonitorService.ListAlertRules:output_type -> api.monitor.v1.ListAlertRulesResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_monitor_v1_monitor_proto_init() }
func file_api_monitor_v1_monitor_proto_init() {
	if File_api_monitor_v1_monitor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_monitor_v1_monitor_proto_rawDesc), len(file_api_monitor_v1_monitor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_monitor_v1_monitor_proto_goTypes,
		DependencyIndexes: file_api_monitor_v1_monitor_proto_depIdxs,
		MessageInfos:      file_api_monitor_v1_monitor_proto_msgTypes,
	}.Build()
	File_api_monitor_v1_monitor_proto = out.File
	file_api_monitor_v1_monitor_proto_goTypes = nil
	file_api_monitor_v1_monitor_proto_depIdxs = nil
}
