// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.1
// source: api/monitor/v1/monitor.proto

package monitorv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationMonitorServiceCreateAlertRule = "/api.monitor.v1.MonitorService/CreateAlertRule"
const OperationMonitorServiceDeleteAlertRule = "/api.monitor.v1.MonitorService/DeleteAlertRule"
const OperationMonitorServiceGetAlertRule = "/api.monitor.v1.MonitorService/GetAlertRule"
const OperationMonitorServiceGetLatestHealthCheck = "/api.monitor.v1.MonitorService/GetLatestHealthCheck"
const OperationMonitorServiceListAlertRules = "/api.monitor.v1.MonitorService/ListAlertRules"
const OperationMonitorServiceListHealthChecks = "/api.monitor.v1.MonitorService/ListHealthChecks"
const OperationMonitorServiceSaveHealthCheck = "/api.monitor.v1.MonitorService/SaveHealthCheck"
const OperationMonitorServiceUpdateAlertRule = "/api.monitor.v1.MonitorService/UpdateAlertRule"

type MonitorServiceHTTPServer interface {
	CreateAlertRule(context.Context, *CreateAlertRuleRequest) (*CreateAlertRuleResponse, error)
	DeleteAlertRule(context.Context, *DeleteAlertRuleRequest) (*DeleteAlertRuleResponse, error)
	GetAlertRule(context.Context, *GetAlertRuleRequest) (*GetAlertRuleResponse, error)
	GetLatestHealthCheck(context.Context, *GetLatestHealthCheckRequest) (*GetLatestHealthCheckResponse, error)
	ListAlertRules(context.Context, *ListAlertRulesRequest) (*ListAlertRulesResponse, error)
	ListHealthChecks(context.Context, *ListHealthChecksRequest) (*ListHealthChecksResponse, error)
	SaveHealthCheck(context.Context, *SaveHealthCheckRequest) (*SaveHealthCheckResponse, error)
	UpdateAlertRule(context.Context, *UpdateAlertRuleRequest) (*UpdateAlertRuleResponse, error)
}

func RegisterMonitorServiceHTTPServer(s *http.Server, srv MonitorServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/health-checks", _MonitorService_SaveHealthCheck0_HTTP_Handler(srv))
	r.GET("/v1/health-checks", _MonitorService_ListHealthChecks0_HTTP_Handler(srv))
	r.GET("/v1/health-checks/latest", _MonitorService_GetLatestHealthCheck0_HTTP_Handler(srv))
	r.POST("/v1/alert-rules", _MonitorService_CreateAlertRule0_HTTP_Handler(srv))
	r.GET("/v1/alert-rules/{id}", _MonitorService_GetAlertRule0_HTTP_Handler(srv))
	r.GET("/v1/alert-rules", _MonitorService_ListAlertRules0_HTTP_Handler(srv))
	r.PUT("/v1/alert-rules/{id}", _MonitorService_UpdateAlertRule0_HTTP_Handler(srv))
	r.DELETE("/v1/alert-rules/{id}", _MonitorService_DeleteAlertRule0_HTTP_Handler(srv))
}

func _MonitorService_SaveHealthCheck0_HTTP_Handler(srv MonitorServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SaveHealthCheckRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMonitorServiceSaveHealthCheck)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SaveHealthCheck(ctx, req.(*SaveHealthCheckRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SaveHealthCheckResponse)
		return ctx.Result(200, reply)
	}
}

func _MonitorService_ListHealthChecks0_HTTP_Handler(srv MonitorServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListHealthChecksRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMonitorServiceListHealthChecks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListHealthChecks(ctx, req.(*ListHealthChecksRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListHealthChecksResponse)
		return ctx.Result(200, reply)
	}
}

func _MonitorService_GetLatestHealthCheck0_HTTP_Handler(srv MonitorServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetLatestHealthCheckRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMonitorServiceGetLatestHealthCheck)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetLatestHealthCheck(ctx, req.(*GetLatestHealthCheckRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetLatestHealthCheckResponse)
		return ctx.Result(200, reply)
	}
}

func _MonitorService_CreateAlertRule0_HTTP_Handler(srv MonitorServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAlertRuleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMonitorServiceCreateAlertRule)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateAlertRule(ctx, req.(*CreateAlertRuleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateAlertRuleResponse)
		return ctx.Result(200, reply)
	}
}

func _MonitorService_GetAlertRule0_HTTP_Handler(srv MonitorServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAlertRuleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMonitorServiceGetAlertRule)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAlertRule(ctx, req.(*GetAlertRuleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetAlertRuleResponse)
		return ctx.Result(200, reply)
	}
}

func _MonitorService_ListAlertRules0_HTTP_Handler(srv MonitorServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAlertRulesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMonitorServiceListAlertRules)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAlertRules(ctx, req.(*ListAlertRulesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAlertRulesResponse)
		return ctx.Result(200, reply)
	}
}

func _MonitorService_UpdateAlertRule0_HTTP_Handler(srv MonitorServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateAlertRuleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMonitorServiceUpdateAlertRule)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateAlertRule(ctx, req.(*UpdateAlertRuleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateAlertRuleResponse)
		return ctx.Result(200, reply)
	}
}

func _MonitorService_DeleteAlertRule0_HTTP_Handler(srv MonitorServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteAlertRuleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMonitorServiceDeleteAlertRule)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteAlertRule(ctx, req.(*DeleteAlertRuleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteAlertRuleResponse)
		return ctx.Result(200, reply)
	}
}

type MonitorServiceHTTPClient interface {
	CreateAlertRule(ctx context.Context, req *CreateAlertRuleRequest, opts ...http.CallOption) (rsp *CreateAlertRuleResponse, err error)
	DeleteAlertRule(ctx context.Context, req *DeleteAlertRuleRequest, opts ...http.CallOption) (rsp *DeleteAlertRuleResponse, err error)
	GetAlertRule(ctx context.Context, req *GetAlertRuleRequest, opts ...http.CallOption) (rsp *GetAlertRuleResponse, err error)
	GetLatestHealthCheck(ctx context.Context, req *GetLatestHealthCheckRequest, opts ...http.CallOption) (rsp *GetLatestHealthCheckResponse, err error)
	ListAlertRules(ctx context.Context, req *ListAlertRulesRequest, opts ...http.CallOption) (rsp *ListAlertRulesResponse, err error)
	ListHealthChecks(ctx context.Context, req *ListHealthChecksRequest, opts ...http.CallOption) (rsp *ListHealthChecksResponse, err error)
	SaveHealthCheck(ctx context.Context, req *SaveHealthCheckRequest, opts ...http.CallOption) (rsp *SaveHealthCheckResponse, err error)
	UpdateAlertRule(ctx context.Context, req *UpdateAlertRuleRequest, opts ...http.CallOption) (rsp *UpdateAlertRuleResponse, err error)
}

type MonitorServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewMonitorServiceHTTPClient(client *http.Client) MonitorServiceHTTPClient {
	return &MonitorServiceHTTPClientImpl{client}
}

func (c *MonitorServiceHTTPClientImpl) CreateAlertRule(ctx context.Context, in *CreateAlertRuleRequest, opts ...http.CallOption) (*CreateAlertRuleResponse, error) {
	var out CreateAlertRuleResponse
	pattern := "/v1/alert-rules"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMonitorServiceCreateAlertRule))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MonitorServiceHTTPClientImpl) DeleteAlertRule(ctx context.Context, in *DeleteAlertRuleRequest, opts ...http.CallOption) (*DeleteAlertRuleResponse, error) {
	var out DeleteAlertRuleResponse
	pattern := "/v1/alert-rules/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMonitorServiceDeleteAlertRule))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MonitorServiceHTTPClientImpl) GetAlertRule(ctx context.Context, in *GetAlertRuleRequest, opts ...http.CallOption) (*GetAlertRuleResponse, error) {
	var out GetAlertRuleResponse
	pattern := "/v1/alert-rules/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMonitorServiceGetAlertRule))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MonitorServiceHTTPClientImpl) GetLatestHealthCheck(ctx context.Context, in *GetLatestHealthCheckRequest, opts ...http.CallOption) (*GetLatestHealthCheckResponse, error) {
	var out GetLatestHealthCheckResponse
	pattern := "/v1/health-checks/latest"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMonitorServiceGetLatestHealthCheck))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MonitorServiceHTTPClientImpl) ListAlertRules(ctx context.Context, in *ListAlertRulesRequest, opts ...http.CallOption) (*ListAlertRulesResponse, error) {
	var out ListAlertRulesResponse
	pattern := "/v1/alert-rules"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMonitorServiceListAlertRules))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MonitorServiceHTTPClientImpl) ListHealthChecks(ctx context.Context, in *ListHealthChecksRequest, opts ...http.CallOption) (*ListHealthChecksResponse, error) {
	var out ListHealthChecksResponse
	pattern := "/v1/health-checks"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMonitorServiceListHealthChecks))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MonitorServiceHTTPClientImpl) SaveHealthCheck(ctx context.Context, in *SaveHealthCheckRequest, opts ...http.CallOption) (*SaveHealthCheckResponse, error) {
	var out SaveHealthCheckResponse
	pattern := "/v1/health-checks"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMonitorServiceSaveHealthCheck))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MonitorServiceHTTPClientImpl) UpdateAlertRule(ctx context.Context, in *UpdateAlertRuleRequest, opts ...http.CallOption) (*UpdateAlertRuleResponse, error) {
	var out UpdateAlertRuleResponse
	pattern := "/v1/alert-rules/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMonitorServiceUpdateAlertRule))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
