// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.34.1
// source: api/monitor/v1/monitor.proto

package monitorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MonitorService_SaveHealthCheck_FullMethodName      = "/api.monitor.v1.MonitorService/SaveHealthCheck"
	MonitorService_ListHealthChecks_FullMethodName     = "/api.monitor.v1.MonitorService/ListHealthChecks"
	MonitorService_GetLatestHealthCheck_FullMethodName = "/api.monitor.v1.MonitorService/GetLatestHealthCheck"
	MonitorService_CreateAlertRule_FullMethodName      = "/api.monitor.v1.MonitorService/CreateAlertRule"
	MonitorService_GetAlertRule_FullMethodName         = "/api.monitor.v1.MonitorService/GetAlertRule"
	MonitorService_ListAlertRules_FullMethodName       = "/api.monitor.v1.MonitorService/ListAlertRules"
	MonitorService_UpdateAlertRule_FullMethodName      = "/api.monitor.v1.MonitorService/UpdateAlertRule"
	MonitorService_DeleteAlertRule_FullMethodName      = "/api.monitor.v1.MonitorService/DeleteAlertRule"
)

// MonitorServiceClient is the client API for MonitorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MonitorServiceClient interface {
	SaveHealthCheck(ctx context.Context, in *SaveHealthCheckRequest, opts ...grpc.CallOption) (*SaveHealthCheckResponse, error)
	ListHealthChecks(ctx context.Context, in *ListHealthChecksRequest, opts ...grpc.CallOption) (*ListHealthChecksResponse, error)
	GetLatestHealthCheck(ctx context.Context, in *GetLatestHealthCheckRequest, opts ...grpc.CallOption) (*GetLatestHealthCheckResponse, error)
	CreateAlertRule(ctx context.Context, in *CreateAlertRuleRequest, opts ...grpc.CallOption) (*CreateAlertRuleResponse, error)
	GetAlertRule(ctx context.Context, in *GetAlertRuleRequest, opts ...grpc.CallOption) (*GetAlertRuleResponse, error)
	ListAlertRules(ctx context.Context, in *ListAlertRulesRequest, opts ...grpc.CallOption) (*ListAlertRulesResponse, error)
	UpdateAlertRule(ctx context.Context, in *UpdateAlertRuleRequest, opts ...grpc.CallOption) (*UpdateAlertRuleResponse, error)
	DeleteAlertRule(ctx context.Context, in *DeleteAlertRuleRequest, opts ...grpc.CallOption) (*DeleteAlertRuleResponse, error)
}

type monitorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMonitorServiceClient(cc grpc.ClientConnInterface) MonitorServiceClient {
	return &monitorServiceClient{cc}
}

func (c *monitorServiceClient) SaveHealthCheck(ctx context.Context, in *SaveHealthCheckRequest, opts ...grpc.CallOption) (*SaveHealthCheckResponse, error) {
	out := new(SaveHealthCheckResponse)
	err := c.cc.Invoke(ctx, MonitorService_SaveHealthCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) ListHealthChecks(ctx context.Context, in *ListHealthChecksRequest, opts ...grpc.CallOption) (*ListHealthChecksResponse, error) {
	out := new(ListHealthChecksResponse)
	err := c.cc.Invoke(ctx, MonitorService_ListHealthChecks_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) GetLatestHealthCheck(ctx context.Context, in *GetLatestHealthCheckRequest, opts ...grpc.CallOption) (*GetLatestHealthCheckResponse, error) {
	out := new(GetLatestHealthCheckResponse)
	err := c.cc.Invoke(ctx, MonitorService_GetLatestHealthCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) CreateAlertRule(ctx context.Context, in *CreateAlertRuleRequest, opts ...grpc.CallOption) (*CreateAlertRuleResponse, error) {
	out := new(CreateAlertRuleResponse)
	err := c.cc.Invoke(ctx, MonitorService_CreateAlertRule_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) GetAlertRule(ctx context.Context, in *GetAlertRuleRequest, opts ...grpc.CallOption) (*GetAlertRuleResponse, error) {
	out := new(GetAlertRuleResponse)
	err := c.cc.Invoke(ctx, MonitorService_GetAlertRule_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) ListAlertRules(ctx context.Context, in *ListAlertRulesRequest, opts ...grpc.CallOption) (*ListAlertRulesResponse, error) {
	out := new(ListAlertRulesResponse)
	err := c.cc.Invoke(ctx, MonitorService_ListAlertRules_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) UpdateAlertRule(ctx context.Context, in *UpdateAlertRuleRequest, opts ...grpc.CallOption) (*UpdateAlertRuleResponse, error) {
	out := new(UpdateAlertRuleResponse)
	err := c.cc.Invoke(ctx, MonitorService_UpdateAlertRule_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) DeleteAlertRule(ctx context.Context, in *DeleteAlertRuleRequest, opts ...grpc.CallOption) (*DeleteAlertRuleResponse, error) {
	out := new(DeleteAlertRuleResponse)
	err := c.cc.Invoke(ctx, MonitorService_DeleteAlertRule_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonitorServiceServer is the server API for MonitorService service.
// All implementations should embed UnimplementedMonitorServiceServer
// for forward compatibility
type MonitorServiceServer interface {
	SaveHealthCheck(context.Context, *SaveHealthCheckRequest) (*SaveHealthCheckResponse, error)
	ListHealthChecks(context.Context, *ListHealthChecksRequest) (*ListHealthChecksResponse, error)
	GetLatestHealthCheck(context.Context, *GetLatestHealthCheckRequest) (*GetLatestHealthCheckResponse, error)
	CreateAlertRule(context.Context, *CreateAlertRuleRequest) (*CreateAlertRuleResponse, error)
	GetAlertRule(context.Context, *GetAlertRuleRequest) (*GetAlertRuleResponse, error)
	ListAlertRules(context.Context, *ListAlertRulesRequest) (*ListAlertRulesResponse, error)
	UpdateAlertRule(context.Context, *UpdateAlertRuleRequest) (*UpdateAlertRuleResponse, error)
	DeleteAlertRule(context.Context, *DeleteAlertRuleRequest) (*DeleteAlertRuleResponse, error)
}

// UnimplementedMonitorServiceServer should be embedded to have forward compatible implementations.
type UnimplementedMonitorServiceServer struct {
}

func (UnimplementedMonitorServiceServer) SaveHealthCheck(context.Context, *SaveHealthCheckRequest) (*SaveHealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveHealthCheck not implemented")
}
func (UnimplementedMonitorServiceServer) ListHealthChecks(context.Context, *ListHealthChecksRequest) (*ListHealthChecksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHealthChecks not implemented")
}
func (UnimplementedMonitorServiceServer) GetLatestHealthCheck(context.Context, *GetLatestHealthCheckRequest) (*GetLatestHealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestHealthCheck not implemented")
}
func (UnimplementedMonitorServiceServer) CreateAlertRule(context.Context, *CreateAlertRuleRequest) (*CreateAlertRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAlertRule not implemented")
}
func (UnimplementedMonitorServiceServer) GetAlertRule(context.Context, *GetAlertRuleRequest) (*GetAlertRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAlertRule not implemented")
}
func (UnimplementedMonitorServiceServer) ListAlertRules(context.Context, *ListAlertRulesRequest) (*ListAlertRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAlertRules not implemented")
}
func (UnimplementedMonitorServiceServer) UpdateAlertRule(context.Context, *UpdateAlertRuleRequest) (*UpdateAlertRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAlertRule not implemented")
}
func (UnimplementedMonitorServiceServer) DeleteAlertRule(context.Context, *DeleteAlertRuleRequest) (*DeleteAlertRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAlertRule not implemented")
}

// UnsafeMonitorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonitorServiceServer will
// result in compilation errors.
type UnsafeMonitorServiceServer interface {
	mustEmbedUnimplementedMonitorServiceServer()
}

func RegisterMonitorServiceServer(s grpc.ServiceRegistrar, srv MonitorServiceServer) {
	s.RegisterService(&MonitorService_ServiceDesc, srv)
}

func _MonitorService_SaveHealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveHealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).SaveHealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_SaveHealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).SaveHealthCheck(ctx, req.(*SaveHealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_ListHealthChecks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHealthChecksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).ListHealthChecks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_ListHealthChecks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).ListHealthChecks(ctx, req.(*ListHealthChecksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_GetLatestHealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestHealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).GetLatestHealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_GetLatestHealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).GetLatestHealthCheck(ctx, req.(*GetLatestHealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_CreateAlertRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAlertRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).CreateAlertRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_CreateAlertRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).CreateAlertRule(ctx, req.(*CreateAlertRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_GetAlertRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlertRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).GetAlertRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_GetAlertRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).GetAlertRule(ctx, req.(*GetAlertRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_ListAlertRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAlertRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).ListAlertRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_ListAlertRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).ListAlertRules(ctx, req.(*ListAlertRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_UpdateAlertRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAlertRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).UpdateAlertRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_UpdateAlertRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).UpdateAlertRule(ctx, req.(*UpdateAlertRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_DeleteAlertRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAlertRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).DeleteAlertRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_DeleteAlertRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).DeleteAlertRule(ctx, req.(*DeleteAlertRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MonitorService_ServiceDesc is the grpc.ServiceDesc for MonitorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MonitorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.monitor.v1.MonitorService",
	HandlerType: (*MonitorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveHealthCheck",
			Handler:    _MonitorService_SaveHealthCheck_Handler,
		},
		{
			MethodName: "ListHealthChecks",
			Handler:    _MonitorService_ListHealthChecks_Handler,
		},
		{
			MethodName: "GetLatestHealthCheck",
			Handler:    _MonitorService_GetLatestHealthCheck_Handler,
		},
		{
			MethodName: "CreateAlertRule",
			Handler:    _MonitorService_CreateAlertRule_Handler,
		},
		{
			MethodName: "GetAlertRule",
			Handler:    _MonitorService_GetAlertRule_Handler,
		},
		{
			MethodName: "ListAlertRules",
			Handler:    _MonitorService_ListAlertRules_Handler,
		},
		{
			MethodName: "UpdateAlertRule",
			Handler:    _MonitorService_UpdateAlertRule_Handler,
		},
		{
			MethodName: "DeleteAlertRule",
			Handler:    _MonitorService_DeleteAlertRule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/monitor/v1/monitor.proto",
}
