// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.1
// source: api/notify/v1/notify.proto

package notifyv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationNotifyServiceCreateNotification = "/api.notify.v1.NotifyService/CreateNotification"
const OperationNotifyServiceGetNotification = "/api.notify.v1.NotifyService/GetNotification"
const OperationNotifyServiceListNotifications = "/api.notify.v1.NotifyService/ListNotifications"
const OperationNotifyServiceUpdateNotificationStatus = "/api.notify.v1.NotifyService/UpdateNotificationStatus"

type NotifyServiceHTTPServer interface {
	CreateNotification(context.Context, *CreateNotificationRequest) (*CreateNotificationResponse, error)
	GetNotification(context.Context, *GetNotificationRequest) (*GetNotificationResponse, error)
	ListNotifications(context.Context, *ListNotificationsRequest) (*ListNotificationsResponse, error)
	UpdateNotificationStatus(context.Context, *UpdateNotificationStatusRequest) (*UpdateNotificationStatusResponse, error)
}

func RegisterNotifyServiceHTTPServer(s *http.Server, srv NotifyServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/notifications", _NotifyService_CreateNotification0_HTTP_Handler(srv))
	r.GET("/v1/notifications/{id}", _NotifyService_GetNotification0_HTTP_Handler(srv))
	r.GET("/v1/notifications", _NotifyService_ListNotifications0_HTTP_Handler(srv))
	r.PUT("/v1/notifications/{id}/status", _NotifyService_UpdateNotificationStatus0_HTTP_Handler(srv))
}

func _NotifyService_CreateNotification0_HTTP_Handler(srv NotifyServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateNotificationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNotifyServiceCreateNotification)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateNotification(ctx, req.(*CreateNotificationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateNotificationResponse)
		return ctx.Result(200, reply)
	}
}

func _NotifyService_GetNotification0_HTTP_Handler(srv NotifyServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetNotificationRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNotifyServiceGetNotification)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetNotification(ctx, req.(*GetNotificationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetNotificationResponse)
		return ctx.Result(200, reply)
	}
}

func _NotifyService_ListNotifications0_HTTP_Handler(srv NotifyServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListNotificationsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNotifyServiceListNotifications)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListNotifications(ctx, req.(*ListNotificationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListNotificationsResponse)
		return ctx.Result(200, reply)
	}
}

func _NotifyService_UpdateNotificationStatus0_HTTP_Handler(srv NotifyServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateNotificationStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNotifyServiceUpdateNotificationStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateNotificationStatus(ctx, req.(*UpdateNotificationStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateNotificationStatusResponse)
		return ctx.Result(200, reply)
	}
}

type NotifyServiceHTTPClient interface {
	CreateNotification(ctx context.Context, req *CreateNotificationRequest, opts ...http.CallOption) (rsp *CreateNotificationResponse, err error)
	GetNotification(ctx context.Context, req *GetNotificationRequest, opts ...http.CallOption) (rsp *GetNotificationResponse, err error)
	ListNotifications(ctx context.Context, req *ListNotificationsRequest, opts ...http.CallOption) (rsp *ListNotificationsResponse, err error)
	UpdateNotificationStatus(ctx context.Context, req *UpdateNotificationStatusRequest, opts ...http.CallOption) (rsp *UpdateNotificationStatusResponse, err error)
}

type NotifyServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewNotifyServiceHTTPClient(client *http.Client) NotifyServiceHTTPClient {
	return &NotifyServiceHTTPClientImpl{client}
}

func (c *NotifyServiceHTTPClientImpl) CreateNotification(ctx context.Context, in *CreateNotificationRequest, opts ...http.CallOption) (*CreateNotificationResponse, error) {
	var out CreateNotificationResponse
	pattern := "/v1/notifications"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationNotifyServiceCreateNotification))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *NotifyServiceHTTPClientImpl) GetNotification(ctx context.Context, in *GetNotificationRequest, opts ...http.CallOption) (*GetNotificationResponse, error) {
	var out GetNotificationResponse
	pattern := "/v1/notifications/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationNotifyServiceGetNotification))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *NotifyServiceHTTPClientImpl) ListNotifications(ctx context.Context, in *ListNotificationsRequest, opts ...http.CallOption) (*ListNotificationsResponse, error) {
	var out ListNotificationsResponse
	pattern := "/v1/notifications"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationNotifyServiceListNotifications))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *NotifyServiceHTTPClientImpl) UpdateNotificationStatus(ctx context.Context, in *UpdateNotificationStatusRequest, opts ...http.CallOption) (*UpdateNotificationStatusResponse, error) {
	var out UpdateNotificationStatusResponse
	pattern := "/v1/notifications/{id}/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationNotifyServiceUpdateNotificationStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
