// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/notify/v1/notify.proto

package notifyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Recipient     string                 `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNotificationRequest) Reset() {
	*x = CreateNotificationRequest{}
	mi := &file_api_notify_v1_notify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotificationRequest) ProtoMessage() {}

func (x *CreateNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotificationRequest.ProtoReflect.Descriptor instead.
func (*CreateNotificationRequest) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNotificationRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateNotificationRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *CreateNotificationRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CreateNotificationRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type NotificationItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Recipient     string                 `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Subject       string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	RetryCount    int32                  `protobuf:"varint,7,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SentAt        int64                  `protobuf:"varint,9,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationItem) Reset() {
	*x = NotificationItem{}
	mi := &file_api_notify_v1_notify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationItem) ProtoMessage() {}

func (x *NotificationItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationItem.ProtoReflect.Descriptor instead.
func (*NotificationItem) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NotificationItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NotificationItem) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *NotificationItem) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *NotificationItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NotificationItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NotificationItem) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *NotificationItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *NotificationItem) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

type CreateNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  *NotificationItem      `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNotificationResponse) Reset() {
	*x = CreateNotificationResponse{}
	mi := &file_api_notify_v1_notify_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotificationResponse) ProtoMessage() {}

func (x *CreateNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotificationResponse.ProtoReflect.Descriptor instead.
func (*CreateNotificationResponse) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{2}
}

func (x *CreateNotificationResponse) GetNotification() *NotificationItem {
	if x != nil {
		return x.Notification
	}
	return nil
}

type GetNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationRequest) Reset() {
	*x = GetNotificationRequest{}
	mi := &file_api_notify_v1_notify_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationRequest) ProtoMessage() {}

func (x *GetNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationRequest) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{3}
}

func (x *GetNotificationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  *NotificationItem      `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationResponse) Reset() {
	*x = GetNotificationResponse{}
	mi := &file_api_notify_v1_notify_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationResponse) ProtoMessage() {}

func (x *GetNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationResponse.ProtoReflect.Descriptor instead.
func (*GetNotificationResponse) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{4}
}

func (x *GetNotificationResponse) GetNotification() *NotificationItem {
	if x != nil {
		return x.Notification
	}
	return nil
}

type ListNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsRequest) Reset() {
	*x = ListNotificationsRequest{}
	mi := &file_api_notify_v1_notify_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsRequest) ProtoMessage() {}

func (x *ListNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{5}
}

func (x *ListNotificationsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListNotificationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListNotificationsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListNotificationsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*NotificationItem    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsResponse) Reset() {
	*x = ListNotificationsResponse{}
	mi := &file_api_notify_v1_notify_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsResponse) ProtoMessage() {}

func (x *ListNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsResponse.ProtoReflect.Descriptor instead.
func (*ListNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{6}
}

func (x *ListNotificationsResponse) GetItems() []*NotificationItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListNotificationsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateNotificationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationStatusRequest) Reset() {
	*x = UpdateNotificationStatusRequest{}
	mi := &file_api_notify_v1_notify_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationStatusRequest) ProtoMessage() {}

func (x *UpdateNotificationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateNotificationStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateNotificationStatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateNotificationStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateNotificationStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationStatusResponse) Reset() {
	*x = UpdateNotificationStatusResponse{}
	mi := &file_api_notify_v1_notify_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationStatusResponse) ProtoMessage() {}

func (x *UpdateNotificationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notify_v1_notify_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateNotificationStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_notify_v1_notify_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateNotificationStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_notify_v1_notify_proto protoreflect.FileDescriptor

const file_api_notify_v1_notify_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/notify/v1/notify.proto\x12\rapi.notify.v1\"\x81\x01\n" +
	"\x19CreateNotificationRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1c\n" +
	"\trecipient\x18\x02 \x01(\tR\trecipient\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"\xf9\x01\n" +
	"\x10NotificationItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1c\n" +
	"\trecipient\x18\x03 \x01(\tR\trecipient\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1f\n" +
	"\vretry_count\x18\a \x01(\x05R\n" +
	"retryCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x17\n" +
	"\asent_at\x18\t \x01(\x03R\x06sentAt\"a\n" +
	"\x1aCreateNotificationResponse\x12C\n" +
	"\fnotification\x18\x01 \x01(\v2\x1f.api.notify.v1.NotificationItemR\fnotification\"(\n" +
	"\x16GetNotificationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"^\n" +
	"\x17GetNotificationResponse\x12C\n" +
	"\fnotification\x18\x01 \x01(\v2\x1f.api.notify.v1.NotificationItemR\fnotification\"w\n" +
	"\x18ListNotificationsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"h\n" +
	"\x19ListNotificationsResponse\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.api.notify.v1.NotificationItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"I\n" +
	"\x1fUpdateNotificationStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"<\n" +
	" UpdateNotificationStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xc1\x03\n" +
	"\rNotifyService\x12i\n" +
	"\x12CreateNotification\x12(.api.notify.v1.CreateNotificationRequest\x1a).api.notify.v1.CreateNotificationResponse\x12`\n" +
	"\x0fGetNotification\x12%.api.notify.v1.GetNotificationRequest\x1a&.api.notify.v1.GetNotificationResponse\x12f\n" +
	"\x11ListNotifications\x12'.api.notify.v1.ListNotificationsRequest\x1a(.api.notify.v1.ListNotificationsResponse\x12{\n" +
	"\x18UpdateNotificationStatus\x12..api.notify.v1.UpdateNotificationStatusRequest\x1a/.api.notify.v1.UpdateNotificationStatusResponseB&Z$micro-one-api/api/notify/v1;notifyv1b\x06proto3"

var (
	file_api_notify_v1_notify_proto_rawDescOnce sync.Once
	file_api_notify_v1_notify_proto_rawDescData []byte
)

func file_api_notify_v1_notify_proto_rawDescGZIP() []byte {
	file_api_notify_v1_notify_proto_rawDescOnce.Do(func() {
		file_api_notify_v1_notify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_notify_v1_notify_proto_rawDesc), len(file_api_notify_v1_notify_proto_rawDesc)))
	})
	return file_api_notify_v1_notify_proto_rawDescData
}

var file_api_notify_v1_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_notify_v1_notify_proto_goTypes = []any{
	(*CreateNotificationRequest)(nil),        // 0: api.notify.v1.CreateNotificationRequest
	(*NotificationItem)(nil),                 // 1: api.notify.v1.NotificationItem
	(*CreateNotificationResponse)(nil),       // 2: api.notify.v1.CreateNotificationResponse
	(*GetNotificationRequest)(nil),           // 3: api.notify.v1.GetNotificationRequest
	(*GetNotificationResponse)(nil),          // 4: api.notify.v1.GetNotificationResponse
	(*ListNotificationsRequest)(nil),         // 5: api.notify.v1.ListNotificationsRequest
	(*ListNotificationsResponse)(nil),        // 6: api.notify.v1.ListNotificationsResponse
	(*UpdateNotificationStatusRequest)(nil),  // 7: api.notify.v1.UpdateNotificationStatusRequest
	(*UpdateNotificationStatusResponse)(nil), // 8: api.notify.v1.UpdateNotificationStatusResponse
}
var file_api_notify_v1_notify_proto_depIdxs = []int32{
	1, // 0: api.notify.v1.CreateNotificationResponse.notification:type_name -> api.notify.v1.NotificationItem
	1, // 1: api.notify.v1.GetNotificationResponse.notification:type_name -> api.notify.v1.NotificationItem
	1, // 2: api.notify.v1.ListNotificationsResponse.items:type_name -> api.notify.v1.NotificationItem
	0, // 3: api.notify.v1.NotifyService.CreateNotification:input_type -> api.notify.v1.CreateNotificationRequest
	3, // 4: api.notify.v1.NotifyService.GetNotification:input_type -> api.notify.v1.GetNotificationRequest
	5, // 5: api.notify.v1.NotifyService.ListNotifications:input_type -> api.notify.v1.ListNotificationsRequest
	7, // 6: api.notify.v1.NotifyService.UpdateNotificationStatus:input_type -> api.notify.v1.UpdateNotificationStatusRequest
	2, // 7: api.notify.v1.NotifyService.CreateNotification:output_type -> api.notify.v1.CreateNotificationResponse
	4, // 8: api.notify.v1.NotifyService.GetNotification:output_type -> api.notify.v1.GetNotificationResponse
	6, // 9: api.notify.v1.NotifyService.ListNotifications:output_type -> api.notify.v1.ListNotificationsResponse
	8, // 10: api.notify.v1.NotifyService.UpdateNotificationStatus:output_type -> api.notify.v1.UpdateNotificationStatusResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_notify_v1_notify_proto_init() }
func file_api_notify_v1_notify_proto_init() {
	if File_api_notify_v1_notify_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_notify_v1_notify_proto_rawDesc), len(file_api_notify_v1_notify_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_notify_v1_notify_proto_goTypes,
		DependencyIndexes: file_api_notify_v1_notify_proto_depIdxs,
		MessageInfos:      file_api_notify_v1_notify_proto_msgTypes,
	}.Build()
	File_api_notify_v1_notify_proto = out.File
	file_api_notify_v1_notify_proto_goTypes = nil
	file_api_notify_v1_notify_proto_depIdxs = nil
}
