// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.1
// source: api/admin/v1/admin.proto

package adminv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAdminServiceGetAccountSnapshot = "/api.admin.v1.AdminService/GetAccountSnapshot"
const OperationAdminServiceGetSystemOptions = "/api.admin.v1.AdminService/GetSystemOptions"
const OperationAdminServiceListChannels = "/api.admin.v1.AdminService/ListChannels"
const OperationAdminServiceListLogs = "/api.admin.v1.AdminService/ListLogs"
const OperationAdminServiceListRedeemCodes = "/api.admin.v1.AdminService/ListRedeemCodes"
const OperationAdminServiceListUsers = "/api.admin.v1.AdminService/ListUsers"
const OperationAdminServiceUpdateSystemOptions = "/api.admin.v1.AdminService/UpdateSystemOptions"

type AdminServiceHTTPServer interface {
	GetAccountSnapshot(context.Context, *GetAccountSnapshotRequest) (*AdminAccountSnapshotResponse, error)
	// GetSystemOptions ========== 系统配置管理 ==========
	GetSystemOptions(context.Context, *GetSystemOptionsRequest) (*GetSystemOptionsResponse, error)
	// ListChannels ========== 渠道管理（透传 channel-service）==========
	ListChannels(context.Context, *AdminListChannelsRequest) (*AdminListChannelsResponse, error)
	// ListLogs ========== 日志查询 ==========
	ListLogs(context.Context, *ListLogsRequest) (*ListLogsResponse, error)
	ListRedeemCodes(context.Context, *ListRedeemCodesRequest) (*ListRedeemCodesResponse, error)
	// ListUsers ========== 用户管理（透传 identity-service）==========
	ListUsers(context.Context, *AdminListUsersRequest) (*AdminListUsersResponse, error)
	UpdateSystemOptions(context.Context, *UpdateSystemOptionsRequest) (*UpdateSystemOptionsResponse, error)
}

func RegisterAdminServiceHTTPServer(s *http.Server, srv AdminServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/redeem-codes", _AdminService_ListRedeemCodes0_HTTP_Handler(srv))
	r.GET("/v1/account", _AdminService_GetAccountSnapshot0_HTTP_Handler(srv))
	r.GET("/v1/users", _AdminService_ListUsers0_HTTP_Handler(srv))
	r.GET("/v1/channels", _AdminService_ListChannels0_HTTP_Handler(srv))
	r.GET("/v1/system/options", _AdminService_GetSystemOptions0_HTTP_Handler(srv))
	r.PUT("/v1/system/options", _AdminService_UpdateSystemOptions0_HTTP_Handler(srv))
	r.GET("/v1/logs", _AdminService_ListLogs0_HTTP_Handler(srv))
}

func _AdminService_ListRedeemCodes0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRedeemCodesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListRedeemCodes)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRedeemCodes(ctx, req.(*ListRedeemCodesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRedeemCodesResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_GetAccountSnapshot0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAccountSnapshotRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceGetAccountSnapshot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAccountSnapshot(ctx, req.(*GetAccountSnapshotRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminAccountSnapshotResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListUsers0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AdminListUsersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListUsers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListUsers(ctx, req.(*AdminListUsersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminListUsersResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListChannels0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AdminListChannelsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListChannels)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListChannels(ctx, req.(*AdminListChannelsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminListChannelsResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_GetSystemOptions0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSystemOptionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceGetSystemOptions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSystemOptions(ctx, req.(*GetSystemOptionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSystemOptionsResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_UpdateSystemOptions0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateSystemOptionsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceUpdateSystemOptions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateSystemOptions(ctx, req.(*UpdateSystemOptionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateSystemOptionsResponse)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListLogs0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListLogsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListLogs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListLogs(ctx, req.(*ListLogsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListLogsResponse)
		return ctx.Result(200, reply)
	}
}

type AdminServiceHTTPClient interface {
	GetAccountSnapshot(ctx context.Context, req *GetAccountSnapshotRequest, opts ...http.CallOption) (rsp *AdminAccountSnapshotResponse, err error)
	// GetSystemOptions ========== 系统配置管理 ==========
	GetSystemOptions(ctx context.Context, req *GetSystemOptionsRequest, opts ...http.CallOption) (rsp *GetSystemOptionsResponse, err error)
	// ListChannels ========== 渠道管理（透传 channel-service）==========
	ListChannels(ctx context.Context, req *AdminListChannelsRequest, opts ...http.CallOption) (rsp *AdminListChannelsResponse, err error)
	// ListLogs ========== 日志查询 ==========
	ListLogs(ctx context.Context, req *ListLogsRequest, opts ...http.CallOption) (rsp *ListLogsResponse, err error)
	ListRedeemCodes(ctx context.Context, req *ListRedeemCodesRequest, opts ...http.CallOption) (rsp *ListRedeemCodesResponse, err error)
	// ListUsers ========== 用户管理（透传 identity-service）==========
	ListUsers(ctx context.Context, req *AdminListUsersRequest, opts ...http.CallOption) (rsp *AdminListUsersResponse, err error)
	UpdateSystemOptions(ctx context.Context, req *UpdateSystemOptionsRequest, opts ...http.CallOption) (rsp *UpdateSystemOptionsResponse, err error)
}

type AdminServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAdminServiceHTTPClient(client *http.Client) AdminServiceHTTPClient {
	return &AdminServiceHTTPClientImpl{client}
}

func (c *AdminServiceHTTPClientImpl) GetAccountSnapshot(ctx context.Context, in *GetAccountSnapshotRequest, opts ...http.CallOption) (*AdminAccountSnapshotResponse, error) {
	var out AdminAccountSnapshotResponse
	pattern := "/v1/account"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminServiceGetAccountSnapshot))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSystemOptions ========== 系统配置管理 ==========
func (c *AdminServiceHTTPClientImpl) GetSystemOptions(ctx context.Context, in *GetSystemOptionsRequest, opts ...http.CallOption) (*GetSystemOptionsResponse, error) {
	var out GetSystemOptionsResponse
	pattern := "/v1/system/options"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminServiceGetSystemOptions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListChannels ========== 渠道管理（透传 channel-service）==========
func (c *AdminServiceHTTPClientImpl) ListChannels(ctx context.Context, in *AdminListChannelsRequest, opts ...http.CallOption) (*AdminListChannelsResponse, error) {
	var out AdminListChannelsResponse
	pattern := "/v1/channels"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminServiceListChannels))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListLogs ========== 日志查询 ==========
func (c *AdminServiceHTTPClientImpl) ListLogs(ctx context.Context, in *ListLogsRequest, opts ...http.CallOption) (*ListLogsResponse, error) {
	var out ListLogsResponse
	pattern := "/v1/logs"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminServiceListLogs))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListRedeemCodes(ctx context.Context, in *ListRedeemCodesRequest, opts ...http.CallOption) (*ListRedeemCodesResponse, error) {
	var out ListRedeemCodesResponse
	pattern := "/v1/redeem-codes"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminServiceListRedeemCodes))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListUsers ========== 用户管理（透传 identity-service）==========
func (c *AdminServiceHTTPClientImpl) ListUsers(ctx context.Context, in *AdminListUsersRequest, opts ...http.CallOption) (*AdminListUsersResponse, error) {
	var out AdminListUsersResponse
	pattern := "/v1/users"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdminServiceListUsers))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) UpdateSystemOptions(ctx context.Context, in *UpdateSystemOptionsRequest, opts ...http.CallOption) (*UpdateSystemOptionsResponse, error) {
	var out UpdateSystemOptionsResponse
	pattern := "/v1/system/options"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAdminServiceUpdateSystemOptions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
