-- Phase 3 table partitioning index (manual, MySQL 8.0 only).
--
-- The target tables live in different service-owned schemas and use different
-- created_at storage types. Do NOT execute one combined file against a single
-- schema. Follow docs/runbooks/table-partitioning-runbook.md and apply:
--
--   migrations/manual/phase3_logs_partitioning.sql
--     against oneapi_log
--
--   migrations/manual/phase3_billing_ledgers_partitioning.sql
--     against oneapi_billing
--
-- Runtime maintenance is implemented by platform/database/partition. No MySQL
-- EVENTs or stored procedures are installed; enabling both an EVENT and the
-- service ticker would race to create the same monthly partition.
