ALTER TABLE notifications ADD COLUMN acknowledged_at BIGINT NOT NULL DEFAULT 0;
ALTER TABLE notifications ADD COLUMN acknowledged_by BIGINT NOT NULL DEFAULT 0;
ALTER TABLE notifications ADD COLUMN revision BIGINT NOT NULL DEFAULT 1;
CREATE TABLE notification_rules (
 id BIGINT PRIMARY KEY,
 name VARCHAR(160) NOT NULL,
 event VARCHAR(160) NOT NULL,
 type VARCHAR(32) NOT NULL,
 recipient TEXT NOT NULL,
 enabled BIGINT NOT NULL DEFAULT 1,
 revision BIGINT NOT NULL DEFAULT 1
);
