// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: billing/v1/billing.proto

package billingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BillingService_ReserveQuota_FullMethodName       = "/api.billing.v1.BillingService/ReserveQuota"
	BillingService_CommitQuota_FullMethodName        = "/api.billing.v1.BillingService/CommitQuota"
	BillingService_ReleaseQuota_FullMethodName       = "/api.billing.v1.BillingService/ReleaseQuota"
	BillingService_GetAccountSnapshot_FullMethodName = "/api.billing.v1.BillingService/GetAccountSnapshot"
)

// BillingServiceClient is the client API for BillingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BillingServiceClient interface {
	ReserveQuota(ctx context.Context, in *ReserveQuotaRequest, opts ...grpc.CallOption) (*ReserveQuotaReply, error)
	CommitQuota(ctx context.Context, in *CommitQuotaRequest, opts ...grpc.CallOption) (*CommitQuotaReply, error)
	ReleaseQuota(ctx context.Context, in *ReleaseQuotaRequest, opts ...grpc.CallOption) (*ReleaseQuotaReply, error)
	GetAccountSnapshot(ctx context.Context, in *GetAccountSnapshotRequest, opts ...grpc.CallOption) (*GetAccountSnapshotReply, error)
}

type billingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBillingServiceClient(cc grpc.ClientConnInterface) BillingServiceClient {
	return &billingServiceClient{cc}
}

func (c *billingServiceClient) ReserveQuota(ctx context.Context, in *ReserveQuotaRequest, opts ...grpc.CallOption) (*ReserveQuotaReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveQuotaReply)
	err := c.cc.Invoke(ctx, BillingService_ReserveQuota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) CommitQuota(ctx context.Context, in *CommitQuotaRequest, opts ...grpc.CallOption) (*CommitQuotaReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitQuotaReply)
	err := c.cc.Invoke(ctx, BillingService_CommitQuota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) ReleaseQuota(ctx context.Context, in *ReleaseQuotaRequest, opts ...grpc.CallOption) (*ReleaseQuotaReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseQuotaReply)
	err := c.cc.Invoke(ctx, BillingService_ReleaseQuota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) GetAccountSnapshot(ctx context.Context, in *GetAccountSnapshotRequest, opts ...grpc.CallOption) (*GetAccountSnapshotReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountSnapshotReply)
	err := c.cc.Invoke(ctx, BillingService_GetAccountSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillingServiceServer is the server API for BillingService service.
// All implementations should embed UnimplementedBillingServiceServer
// for forward compatibility.
type BillingServiceServer interface {
	ReserveQuota(context.Context, *ReserveQuotaRequest) (*ReserveQuotaReply, error)
	CommitQuota(context.Context, *CommitQuotaRequest) (*CommitQuotaReply, error)
	ReleaseQuota(context.Context, *ReleaseQuotaRequest) (*ReleaseQuotaReply, error)
	GetAccountSnapshot(context.Context, *GetAccountSnapshotRequest) (*GetAccountSnapshotReply, error)
}

// UnimplementedBillingServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBillingServiceServer struct{}

func (UnimplementedBillingServiceServer) ReserveQuota(context.Context, *ReserveQuotaRequest) (*ReserveQuotaReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ReserveQuota not implemented")
}
func (UnimplementedBillingServiceServer) CommitQuota(context.Context, *CommitQuotaRequest) (*CommitQuotaReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitQuota not implemented")
}
func (UnimplementedBillingServiceServer) ReleaseQuota(context.Context, *ReleaseQuotaRequest) (*ReleaseQuotaReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseQuota not implemented")
}
func (UnimplementedBillingServiceServer) GetAccountSnapshot(context.Context, *GetAccountSnapshotRequest) (*GetAccountSnapshotReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccountSnapshot not implemented")
}
func (UnimplementedBillingServiceServer) testEmbeddedByValue() {}

// UnsafeBillingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BillingServiceServer will
// result in compilation errors.
type UnsafeBillingServiceServer interface {
	mustEmbedUnimplementedBillingServiceServer()
}

func RegisterBillingServiceServer(s grpc.ServiceRegistrar, srv BillingServiceServer) {
	// If the following call panics, it indicates UnimplementedBillingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BillingService_ServiceDesc, srv)
}

func _BillingService_ReserveQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).ReserveQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_ReserveQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).ReserveQuota(ctx, req.(*ReserveQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_CommitQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).CommitQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_CommitQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).CommitQuota(ctx, req.(*CommitQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_ReleaseQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).ReleaseQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_ReleaseQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).ReleaseQuota(ctx, req.(*ReleaseQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_GetAccountSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetAccountSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_GetAccountSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetAccountSnapshot(ctx, req.(*GetAccountSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BillingService_ServiceDesc is the grpc.ServiceDesc for BillingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BillingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.billing.v1.BillingService",
	HandlerType: (*BillingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReserveQuota",
			Handler:    _BillingService_ReserveQuota_Handler,
		},
		{
			MethodName: "CommitQuota",
			Handler:    _BillingService_CommitQuota_Handler,
		},
		{
			MethodName: "ReleaseQuota",
			Handler:    _BillingService_ReleaseQuota_Handler,
		},
		{
			MethodName: "GetAccountSnapshot",
			Handler:    _BillingService_GetAccountSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "billing/v1/billing.proto",
}
