// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: billing/v1/billing.proto

package billingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReserveQuotaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TokenId       int64                  `protobuf:"varint,3,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Quota         int64                  `protobuf:"varint,4,opt,name=quota,proto3" json:"quota,omitempty"`
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveQuotaRequest) Reset() {
	*x = ReserveQuotaRequest{}
	mi := &file_billing_v1_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveQuotaRequest) ProtoMessage() {}

func (x *ReserveQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveQuotaRequest.ProtoReflect.Descriptor instead.
func (*ReserveQuotaRequest) Descriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{0}
}

func (x *ReserveQuotaRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ReserveQuotaRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReserveQuotaRequest) GetTokenId() int64 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

func (x *ReserveQuotaRequest) GetQuota() int64 {
	if x != nil {
		return x.Quota
	}
	return 0
}

func (x *ReserveQuotaRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type ReserveQuotaReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Reserved      bool                   `protobuf:"varint,2,opt,name=reserved,proto3" json:"reserved,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveQuotaReply) Reset() {
	*x = ReserveQuotaReply{}
	mi := &file_billing_v1_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveQuotaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveQuotaReply) ProtoMessage() {}

func (x *ReserveQuotaReply) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveQuotaReply.ProtoReflect.Descriptor instead.
func (*ReserveQuotaReply) Descriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{1}
}

func (x *ReserveQuotaReply) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReserveQuotaReply) GetReserved() bool {
	if x != nil {
		return x.Reserved
	}
	return false
}

func (x *ReserveQuotaReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CommitQuotaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ReservationId string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	ActualQuota   int64                  `protobuf:"varint,3,opt,name=actual_quota,json=actualQuota,proto3" json:"actual_quota,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitQuotaRequest) Reset() {
	*x = CommitQuotaRequest{}
	mi := &file_billing_v1_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitQuotaRequest) ProtoMessage() {}

func (x *CommitQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitQuotaRequest.ProtoReflect.Descriptor instead.
func (*CommitQuotaRequest) Descriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{2}
}

func (x *CommitQuotaRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CommitQuotaRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *CommitQuotaRequest) GetActualQuota() int64 {
	if x != nil {
		return x.ActualQuota
	}
	return 0
}

type CommitQuotaReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Committed     bool                   `protobuf:"varint,1,opt,name=committed,proto3" json:"committed,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitQuotaReply) Reset() {
	*x = CommitQuotaReply{}
	mi := &file_billing_v1_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitQuotaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitQuotaReply) ProtoMessage() {}

func (x *CommitQuotaReply) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitQuotaReply.ProtoReflect.Descriptor instead.
func (*CommitQuotaReply) Descriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{3}
}

func (x *CommitQuotaReply) GetCommitted() bool {
	if x != nil {
		return x.Committed
	}
	return false
}

func (x *CommitQuotaReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReleaseQuotaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ReservationId string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseQuotaRequest) Reset() {
	*x = ReleaseQuotaRequest{}
	mi := &file_billing_v1_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseQuotaRequest) ProtoMessage() {}

func (x *ReleaseQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseQuotaRequest.ProtoReflect.Descriptor instead.
func (*ReleaseQuotaRequest) Descriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{4}
}

func (x *ReleaseQuotaRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ReleaseQuotaRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type ReleaseQuotaReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Released      bool                   `protobuf:"varint,1,opt,name=released,proto3" json:"released,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseQuotaReply) Reset() {
	*x = ReleaseQuotaReply{}
	mi := &file_billing_v1_billing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseQuotaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseQuotaReply) ProtoMessage() {}

func (x *ReleaseQuotaReply) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_billing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseQuotaReply.ProtoReflect.Descriptor instead.
func (*ReleaseQuotaReply) Descriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{5}
}

func (x *ReleaseQuotaReply) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

func (x *ReleaseQuotaReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAccountSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TokenId       int64                  `protobuf:"varint,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountSnapshotRequest) Reset() {
	*x = GetAccountSnapshotRequest{}
	mi := &file_billing_v1_billing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountSnapshotRequest) ProtoMessage() {}

func (x *GetAccountSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_billing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetAccountSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{6}
}

func (x *GetAccountSnapshotRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetAccountSnapshotRequest) GetTokenId() int64 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

type GetAccountSnapshotReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserQuota     int64                  `protobuf:"varint,1,opt,name=user_quota,json=userQuota,proto3" json:"user_quota,omitempty"`
	TokenQuota    int64                  `protobuf:"varint,2,opt,name=token_quota,json=tokenQuota,proto3" json:"token_quota,omitempty"`
	Unlimited     bool                   `protobuf:"varint,3,opt,name=unlimited,proto3" json:"unlimited,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountSnapshotReply) Reset() {
	*x = GetAccountSnapshotReply{}
	mi := &file_billing_v1_billing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountSnapshotReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountSnapshotReply) ProtoMessage() {}

func (x *GetAccountSnapshotReply) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_billing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountSnapshotReply.ProtoReflect.Descriptor instead.
func (*GetAccountSnapshotReply) Descriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{7}
}

func (x *GetAccountSnapshotReply) GetUserQuota() int64 {
	if x != nil {
		return x.UserQuota
	}
	return 0
}

func (x *GetAccountSnapshotReply) GetTokenQuota() int64 {
	if x != nil {
		return x.TokenQuota
	}
	return 0
}

func (x *GetAccountSnapshotReply) GetUnlimited() bool {
	if x != nil {
		return x.Unlimited
	}
	return false
}

var File_billing_v1_billing_proto protoreflect.FileDescriptor

const file_billing_v1_billing_proto_rawDesc = "" +
	"\n" +
	"\x18billing/v1/billing.proto\x12\x0eapi.billing.v1\"\x94\x01\n" +
	"\x13ReserveQuotaRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x19\n" +
	"\btoken_id\x18\x03 \x01(\x03R\atokenId\x12\x14\n" +
	"\x05quota\x18\x04 \x01(\x03R\x05quota\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\"p\n" +
	"\x11ReserveQuotaReply\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x1a\n" +
	"\breserved\x18\x02 \x01(\bR\breserved\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"}\n" +
	"\x12CommitQuotaRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\x12!\n" +
	"\factual_quota\x18\x03 \x01(\x03R\vactualQuota\"J\n" +
	"\x10CommitQuotaReply\x12\x1c\n" +
	"\tcommitted\x18\x01 \x01(\bR\tcommitted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"[\n" +
	"\x13ReleaseQuotaRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\"I\n" +
	"\x11ReleaseQuotaReply\x12\x1a\n" +
	"\breleased\x18\x01 \x01(\bR\breleased\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"O\n" +
	"\x19GetAccountSnapshotRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\btoken_id\x18\x02 \x01(\x03R\atokenId\"w\n" +
	"\x17GetAccountSnapshotReply\x12\x1d\n" +
	"\n" +
	"user_quota\x18\x01 \x01(\x03R\tuserQuota\x12\x1f\n" +
	"\vtoken_quota\x18\x02 \x01(\x03R\n" +
	"tokenQuota\x12\x1c\n" +
	"\tunlimited\x18\x03 \x01(\bR\tunlimited2\xff\x02\n" +
	"\x0eBillingService\x12V\n" +
	"\fReserveQuota\x12#.api.billing.v1.ReserveQuotaRequest\x1a!.api.billing.v1.ReserveQuotaReply\x12S\n" +
	"\vCommitQuota\x12\".api.billing.v1.CommitQuotaRequest\x1a .api.billing.v1.CommitQuotaReply\x12V\n" +
	"\fReleaseQuota\x12#.api.billing.v1.ReleaseQuotaRequest\x1a!.api.billing.v1.ReleaseQuotaReply\x12h\n" +
	"\x12GetAccountSnapshot\x12).api.billing.v1.GetAccountSnapshotRequest\x1a'.api.billing.v1.GetAccountSnapshotReplyB(Z&micro-one-api/api/billing/v1;billingv1b\x06proto3"

var (
	file_billing_v1_billing_proto_rawDescOnce sync.Once
	file_billing_v1_billing_proto_rawDescData []byte
)

func file_billing_v1_billing_proto_rawDescGZIP() []byte {
	file_billing_v1_billing_proto_rawDescOnce.Do(func() {
		file_billing_v1_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_v1_billing_proto_rawDesc), len(file_billing_v1_billing_proto_rawDesc)))
	})
	return file_billing_v1_billing_proto_rawDescData
}

var file_billing_v1_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_billing_v1_billing_proto_goTypes = []any{
	(*ReserveQuotaRequest)(nil),       // 0: api.billing.v1.ReserveQuotaRequest
	(*ReserveQuotaReply)(nil),         // 1: api.billing.v1.ReserveQuotaReply
	(*CommitQuotaRequest)(nil),        // 2: api.billing.v1.CommitQuotaRequest
	(*CommitQuotaReply)(nil),          // 3: api.billing.v1.CommitQuotaReply
	(*ReleaseQuotaRequest)(nil),       // 4: api.billing.v1.ReleaseQuotaRequest
	(*ReleaseQuotaReply)(nil),         // 5: api.billing.v1.ReleaseQuotaReply
	(*GetAccountSnapshotRequest)(nil), // 6: api.billing.v1.GetAccountSnapshotRequest
	(*GetAccountSnapshotReply)(nil),   // 7: api.billing.v1.GetAccountSnapshotReply
}
var file_billing_v1_billing_proto_depIdxs = []int32{
	0, // 0: api.billing.v1.BillingService.ReserveQuota:input_type -> api.billing.v1.ReserveQuotaRequest
	2, // 1: api.billing.v1.BillingService.CommitQuota:input_type -> api.billing.v1.CommitQuotaRequest
	4, // 2: api.billing.v1.BillingService.ReleaseQuota:input_type -> api.billing.v1.ReleaseQuotaRequest
	6, // 3: api.billing.v1.BillingService.GetAccountSnapshot:input_type -> api.billing.v1.GetAccountSnapshotRequest
	1, // 4: api.billing.v1.BillingService.ReserveQuota:output_type -> api.billing.v1.ReserveQuotaReply
	3, // 5: api.billing.v1.BillingService.CommitQuota:output_type -> api.billing.v1.CommitQuotaReply
	5, // 6: api.billing.v1.BillingService.ReleaseQuota:output_type -> api.billing.v1.ReleaseQuotaReply
	7, // 7: api.billing.v1.BillingService.GetAccountSnapshot:output_type -> api.billing.v1.GetAccountSnapshotReply
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_billing_v1_billing_proto_init() }
func file_billing_v1_billing_proto_init() {
	if File_billing_v1_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_v1_billing_proto_rawDesc), len(file_billing_v1_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_v1_billing_proto_goTypes,
		DependencyIndexes: file_billing_v1_billing_proto_depIdxs,
		MessageInfos:      file_billing_v1_billing_proto_msgTypes,
	}.Build()
	File_billing_v1_billing_proto = out.File
	file_billing_v1_billing_proto_goTypes = nil
	file_billing_v1_billing_proto_depIdxs = nil
}
