// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.1
// source: api/log/v1/log.proto

package logv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationLogServiceGetLog = "/api.log.v1.LogService/GetLog"
const OperationLogServiceIngestLog = "/api.log.v1.LogService/IngestLog"
const OperationLogServiceListLogs = "/api.log.v1.LogService/ListLogs"

type LogServiceHTTPServer interface {
	GetLog(context.Context, *GetLogRequest) (*GetLogResponse, error)
	IngestLog(context.Context, *IngestLogRequest) (*IngestLogResponse, error)
	ListLogs(context.Context, *ListLogsRequest) (*ListLogsResponse, error)
}

func RegisterLogServiceHTTPServer(s *http.Server, srv LogServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/logs/{id}", _LogService_GetLog0_HTTP_Handler(srv))
	r.GET("/v1/logs", _LogService_ListLogs1_HTTP_Handler(srv))
	r.POST("/v1/logs", _LogService_IngestLog0_HTTP_Handler(srv))
}

func _LogService_GetLog0_HTTP_Handler(srv LogServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetLogRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLogServiceGetLog)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetLog(ctx, req.(*GetLogRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetLogResponse)
		return ctx.Result(200, reply)
	}
}

func _LogService_ListLogs1_HTTP_Handler(srv LogServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListLogsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLogServiceListLogs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListLogs(ctx, req.(*ListLogsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListLogsResponse)
		return ctx.Result(200, reply)
	}
}

func _LogService_IngestLog0_HTTP_Handler(srv LogServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in IngestLogRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLogServiceIngestLog)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.IngestLog(ctx, req.(*IngestLogRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*IngestLogResponse)
		return ctx.Result(200, reply)
	}
}

type LogServiceHTTPClient interface {
	GetLog(ctx context.Context, req *GetLogRequest, opts ...http.CallOption) (rsp *GetLogResponse, err error)
	IngestLog(ctx context.Context, req *IngestLogRequest, opts ...http.CallOption) (rsp *IngestLogResponse, err error)
	ListLogs(ctx context.Context, req *ListLogsRequest, opts ...http.CallOption) (rsp *ListLogsResponse, err error)
}

type LogServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewLogServiceHTTPClient(client *http.Client) LogServiceHTTPClient {
	return &LogServiceHTTPClientImpl{client}
}

func (c *LogServiceHTTPClientImpl) GetLog(ctx context.Context, in *GetLogRequest, opts ...http.CallOption) (*GetLogResponse, error) {
	var out GetLogResponse
	pattern := "/v1/logs/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLogServiceGetLog))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LogServiceHTTPClientImpl) IngestLog(ctx context.Context, in *IngestLogRequest, opts ...http.CallOption) (*IngestLogResponse, error) {
	var out IngestLogResponse
	pattern := "/v1/logs"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLogServiceIngestLog))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LogServiceHTTPClientImpl) ListLogs(ctx context.Context, in *ListLogsRequest, opts ...http.CallOption) (*ListLogsResponse, error) {
	var out ListLogsResponse
	pattern := "/v1/logs"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLogServiceListLogs))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
