// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.1
// source: api/config/v1/config.proto

package configv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationConfigServiceDeleteConfig = "/api.config.v1.ConfigService/DeleteConfig"
const OperationConfigServiceGetConfig = "/api.config.v1.ConfigService/GetConfig"
const OperationConfigServiceListConfigs = "/api.config.v1.ConfigService/ListConfigs"
const OperationConfigServiceSetConfig = "/api.config.v1.ConfigService/SetConfig"

type ConfigServiceHTTPServer interface {
	DeleteConfig(context.Context, *DeleteConfigRequest) (*DeleteConfigResponse, error)
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	ListConfigs(context.Context, *ListConfigsRequest) (*ListConfigsResponse, error)
	SetConfig(context.Context, *SetConfigRequest) (*SetConfigResponse, error)
}

func RegisterConfigServiceHTTPServer(s *http.Server, srv ConfigServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/configs/{namespace}/{key}", _ConfigService_GetConfig0_HTTP_Handler(srv))
	r.GET("/v1/configs/{namespace}", _ConfigService_ListConfigs0_HTTP_Handler(srv))
	r.PUT("/v1/configs/{namespace}/{key}", _ConfigService_SetConfig0_HTTP_Handler(srv))
	r.DELETE("/v1/configs/{namespace}/{key}", _ConfigService_DeleteConfig0_HTTP_Handler(srv))
}

func _ConfigService_GetConfig0_HTTP_Handler(srv ConfigServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetConfigRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConfigServiceGetConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetConfig(ctx, req.(*GetConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetConfigResponse)
		return ctx.Result(200, reply)
	}
}

func _ConfigService_ListConfigs0_HTTP_Handler(srv ConfigServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListConfigsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConfigServiceListConfigs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListConfigs(ctx, req.(*ListConfigsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListConfigsResponse)
		return ctx.Result(200, reply)
	}
}

func _ConfigService_SetConfig0_HTTP_Handler(srv ConfigServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetConfigRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConfigServiceSetConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetConfig(ctx, req.(*SetConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SetConfigResponse)
		return ctx.Result(200, reply)
	}
}

func _ConfigService_DeleteConfig0_HTTP_Handler(srv ConfigServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteConfigRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConfigServiceDeleteConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteConfig(ctx, req.(*DeleteConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteConfigResponse)
		return ctx.Result(200, reply)
	}
}

type ConfigServiceHTTPClient interface {
	DeleteConfig(ctx context.Context, req *DeleteConfigRequest, opts ...http.CallOption) (rsp *DeleteConfigResponse, err error)
	GetConfig(ctx context.Context, req *GetConfigRequest, opts ...http.CallOption) (rsp *GetConfigResponse, err error)
	ListConfigs(ctx context.Context, req *ListConfigsRequest, opts ...http.CallOption) (rsp *ListConfigsResponse, err error)
	SetConfig(ctx context.Context, req *SetConfigRequest, opts ...http.CallOption) (rsp *SetConfigResponse, err error)
}

type ConfigServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewConfigServiceHTTPClient(client *http.Client) ConfigServiceHTTPClient {
	return &ConfigServiceHTTPClientImpl{client}
}

func (c *ConfigServiceHTTPClientImpl) DeleteConfig(ctx context.Context, in *DeleteConfigRequest, opts ...http.CallOption) (*DeleteConfigResponse, error) {
	var out DeleteConfigResponse
	pattern := "/v1/configs/{namespace}/{key}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationConfigServiceDeleteConfig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConfigServiceHTTPClientImpl) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...http.CallOption) (*GetConfigResponse, error) {
	var out GetConfigResponse
	pattern := "/v1/configs/{namespace}/{key}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationConfigServiceGetConfig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConfigServiceHTTPClientImpl) ListConfigs(ctx context.Context, in *ListConfigsRequest, opts ...http.CallOption) (*ListConfigsResponse, error) {
	var out ListConfigsResponse
	pattern := "/v1/configs/{namespace}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationConfigServiceListConfigs))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConfigServiceHTTPClientImpl) SetConfig(ctx context.Context, in *SetConfigRequest, opts ...http.CallOption) (*SetConfigResponse, error) {
	var out SetConfigResponse
	pattern := "/v1/configs/{namespace}/{key}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationConfigServiceSetConfig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
