// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/config/v1/config.proto

package configv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_api_config_v1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_config_v1_config_proto_rawDescGZIP(), []int{0}
}

func (x *GetConfigRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Comment       string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_api_config_v1_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_config_v1_config_proto_rawDescGZIP(), []int{1}
}

func (x *GetConfigResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetConfigResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetConfigResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetConfigResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetConfigResponse) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *GetConfigResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ListConfigsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigsRequest) Reset() {
	*x = ListConfigsRequest{}
	mi := &file_api_config_v1_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigsRequest) ProtoMessage() {}

func (x *ListConfigsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigsRequest.ProtoReflect.Descriptor instead.
func (*ListConfigsRequest) Descriptor() ([]byte, []int) {
	return file_api_config_v1_config_proto_rawDescGZIP(), []int{2}
}

func (x *ListConfigsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListConfigsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListConfigsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListConfigsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*GetConfigResponse   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigsResponse) Reset() {
	*x = ListConfigsResponse{}
	mi := &file_api_config_v1_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigsResponse) ProtoMessage() {}

func (x *ListConfigsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigsResponse.ProtoReflect.Descriptor instead.
func (*ListConfigsResponse) Descriptor() ([]byte, []int) {
	return file_api_config_v1_config_proto_rawDescGZIP(), []int{3}
}

func (x *ListConfigsResponse) GetItems() []*GetConfigResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListConfigsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigRequest) Reset() {
	*x = SetConfigRequest{}
	mi := &file_api_config_v1_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigRequest) ProtoMessage() {}

func (x *SetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigRequest.ProtoReflect.Descriptor instead.
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_config_v1_config_proto_rawDescGZIP(), []int{4}
}

func (x *SetConfigRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SetConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetConfigRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetConfigRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type SetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigResponse) Reset() {
	*x = SetConfigResponse{}
	mi := &file_api_config_v1_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigResponse) ProtoMessage() {}

func (x *SetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigResponse.ProtoReflect.Descriptor instead.
func (*SetConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_config_v1_config_proto_rawDescGZIP(), []int{5}
}

func (x *SetConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfigRequest) Reset() {
	*x = DeleteConfigRequest{}
	mi := &file_api_config_v1_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigRequest) ProtoMessage() {}

func (x *DeleteConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigRequest.ProtoReflect.Descriptor instead.
func (*DeleteConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_config_v1_config_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteConfigRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeleteConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfigResponse) Reset() {
	*x = DeleteConfigResponse{}
	mi := &file_api_config_v1_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigResponse) ProtoMessage() {}

func (x *DeleteConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_config_v1_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigResponse.ProtoReflect.Descriptor instead.
func (*DeleteConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_config_v1_config_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_config_v1_config_proto protoreflect.FileDescriptor

const file_api_config_v1_config_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/config/v1/config.proto\x12\rapi.config.v1\"B\n" +
	"\x10GetConfigRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\xa2\x01\n" +
	"\x11GetConfigResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\"c\n" +
	"\x12ListConfigsRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"c\n" +
	"\x13ListConfigsResponse\x126\n" +
	"\x05items\x18\x01 \x03(\v2 .api.config.v1.GetConfigResponseR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"r\n" +
	"\x10SetConfigRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\"-\n" +
	"\x11SetConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"E\n" +
	"\x13DeleteConfigRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"0\n" +
	"\x14DeleteConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xde\x02\n" +
	"\rConfigService\x12N\n" +
	"\tGetConfig\x12\x1f.api.config.v1.GetConfigRequest\x1a .api.config.v1.GetConfigResponse\x12T\n" +
	"\vListConfigs\x12!.api.config.v1.ListConfigsRequest\x1a\".api.config.v1.ListConfigsResponse\x12N\n" +
	"\tSetConfig\x12\x1f.api.config.v1.SetConfigRequest\x1a .api.config.v1.SetConfigResponse\x12W\n" +
	"\fDeleteConfig\x12\".api.config.v1.DeleteConfigRequest\x1a#.api.config.v1.DeleteConfigResponseB&Z$micro-one-api/api/config/v1;configv1b\x06proto3"

var (
	file_api_config_v1_config_proto_rawDescOnce sync.Once
	file_api_config_v1_config_proto_rawDescData []byte
)

func file_api_config_v1_config_proto_rawDescGZIP() []byte {
	file_api_config_v1_config_proto_rawDescOnce.Do(func() {
		file_api_config_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_config_v1_config_proto_rawDesc), len(file_api_config_v1_config_proto_rawDesc)))
	})
	return file_api_config_v1_config_proto_rawDescData
}

var file_api_config_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_config_v1_config_proto_goTypes = []any{
	(*GetConfigRequest)(nil),     // 0: api.config.v1.GetConfigRequest
	(*GetConfigResponse)(nil),    // 1: api.config.v1.GetConfigResponse
	(*ListConfigsRequest)(nil),   // 2: api.config.v1.ListConfigsRequest
	(*ListConfigsResponse)(nil),  // 3: api.config.v1.ListConfigsResponse
	(*SetConfigRequest)(nil),     // 4: api.config.v1.SetConfigRequest
	(*SetConfigResponse)(nil),    // 5: api.config.v1.SetConfigResponse
	(*DeleteConfigRequest)(nil),  // 6: api.config.v1.DeleteConfigRequest
	(*DeleteConfigResponse)(nil), // 7: api.config.v1.DeleteConfigResponse
}
var file_api_config_v1_config_proto_depIdxs = []int32{
	1, // 0: api.config.v1.ListConfigsResponse.items:type_name -> api.config.v1.GetConfigResponse
	0, // 1: api.config.v1.ConfigService.GetConfig:input_type -> api.config.v1.GetConfigRequest
	2, // 2: api.config.v1.ConfigService.ListConfigs:input_type -> api.config.v1.ListConfigsRequest
	4, // 3: api.config.v1.ConfigService.SetConfig:input_type -> api.config.v1.SetConfigRequest
	6, // 4: api.config.v1.ConfigService.DeleteConfig:input_type -> api.config.v1.DeleteConfigRequest
	1, // 5: api.config.v1.ConfigService.GetConfig:output_type -> api.config.v1.GetConfigResponse
	3, // 6: api.config.v1.ConfigService.ListConfigs:output_type -> api.config.v1.ListConfigsResponse
	5, // 7: api.config.v1.ConfigService.SetConfig:output_type -> api.config.v1.SetConfigResponse
	7, // 8: api.config.v1.ConfigService.DeleteConfig:output_type -> api.config.v1.DeleteConfigResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_config_v1_config_proto_init() }
func file_api_config_v1_config_proto_init() {
	if File_api_config_v1_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_config_v1_config_proto_rawDesc), len(file_api_config_v1_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_config_v1_config_proto_goTypes,
		DependencyIndexes: file_api_config_v1_config_proto_depIdxs,
		MessageInfos:      file_api_config_v1_config_proto_msgTypes,
	}.Build()
	File_api_config_v1_config_proto = out.File
	file_api_config_v1_config_proto_goTypes = nil
	file_api_config_v1_config_proto_depIdxs = nil
}
