package serviceidentity

// RPCPolicy is an exact method contract. A new RPC requires explicit review.
type RPCPolicy struct {
	Owner         string
	UserCallers   []string
	SystemCallers []string
}

var rpcPolicies = map[string]RPCPolicy{
	"/api.admin.v1.AdminService/TopUpQuota":                                  {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.AdminService/CreateRedeemCode":                            {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.AdminService/CreateRedeemCodesBatch":                      {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.AdminService/GetRedeemCode":                               {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.AdminService/ListRedeemCodes":                             {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.AdminService/SearchRedeemCodes":                           {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.AdminService/UpdateRedeemCode":                            {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.AdminService/DeleteRedeemCode":                            {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.AdminService/ListUserLedger":                              {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.AdminService/GetAccountSnapshot":                          {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.AdminService/ListUsers":                                   {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.AdminService/CreateUser":                                  {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.AdminService/UpdateUser":                                  {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.AdminService/DeleteUser":                                  {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.AdminService/ResetUserQuota":                              {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.AdminService/SetUserRole":                                 {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.AdminService/ListChannels":                                {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.AdminService/CreateChannel":                               {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.AdminService/UpdateChannel":                               {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.AdminService/DeleteChannel":                               {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.AdminService/ChangeChannelStatus":                         {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.AdminService/ListSubscriptionAccounts":                    {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.AdminService/CreateSubscriptionAccount":                   {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.AdminService/UpdateSubscriptionAccount":                   {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.AdminService/DeleteSubscriptionAccount":                   {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.AdminService/ChangeSubscriptionAccountStatus":             {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.AdminService/ResetSubscriptionAccountQuota":               {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.AdminService/GetSystemOptions":                            {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.AdminService/UpdateSystemOptions":                         {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.AdminService/ListLogs":                                    {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.AdminService/ListModelRoutings":                           {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.AdminService/UpsertModelRouting":                          {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.AdminService/DeleteModelRouting":                          {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.identity.v1.IdentityService/GetUserRoutingFacts":                   {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{"relay"}},
	"/api.identity.v1.IdentityService/UpdateUserRoutingAccess":               {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IdentityService/SetTokenRouting":                       {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IdentityService/ValidateToken":                         {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{"admin"}},
	"/api.identity.v1.IdentityService/GetAuthSnapshot":                       {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{"relay"}},
	"/api.identity.v1.IdentityService/GetUser":                               {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IdentityService/Login":                                 {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IdentityService/Register":                              {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IdentityService/CreateAccessToken":                     {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IdentityService/ListUsers":                             {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IdentityService/CreateUser":                            {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IdentityService/UpdateUser":                            {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IdentityService/DeleteUser":                            {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IdentityService/SetUserRole":                           {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IdentityService/ConsumeTokenQuota":                     {Owner: "identity", UserCallers: []string{}, SystemCallers: []string{"relay", "billing"}},
	"/api.channel.v1.ChannelService/SetRoutingGroupState":                    {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/ListRoutingGroups":                       {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{"identity"}},
	"/api.channel.v1.ChannelService/GetRoutingGroup":                         {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{"relay", "identity", "billing"}},
	"/api.channel.v1.ChannelService/CreateRoutingGroup":                      {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/CheckRoute":                              {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{"relay"}},
	"/api.channel.v1.ChannelService/SelectChannel":                           {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{"relay"}},
	"/api.channel.v1.ChannelService/SelectSubscriptionAccount":               {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{"relay"}},
	"/api.channel.v1.ChannelService/SetRoutingGroupResourceOverrides":        {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/HasRoutingCandidates":                    {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{"relay"}},
	"/api.channel.v1.ChannelService/GetSubscriptionAccount":                  {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{"relay"}},
	"/api.channel.v1.ChannelService/GetSubscriptionAccountWithSecrets":       {Owner: "channel", UserCallers: []string{}, SystemCallers: []string{"relay"}},
	"/api.channel.v1.ChannelService/ListSubscriptionAccounts":                {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/ListOAuthRefreshCandidates":              {Owner: "channel", UserCallers: []string{}, SystemCallers: []string{"relay", "channel"}},
	"/api.channel.v1.ChannelService/ClearSubscriptionAccountError":           {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{"relay"}},
	"/api.channel.v1.ChannelService/SetSubscriptionAccountError":             {Owner: "channel", UserCallers: []string{}, SystemCallers: []string{"relay", "channel"}},
	"/api.channel.v1.ChannelService/SetTempUnschedulable":                    {Owner: "channel", UserCallers: []string{}, SystemCallers: []string{"relay", "channel"}},
	"/api.channel.v1.ChannelService/ClearTempUnschedulable":                  {Owner: "channel", UserCallers: []string{}, SystemCallers: []string{"relay", "channel"}},
	"/api.channel.v1.ChannelService/CreateSubscriptionAccount":               {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/StoreSubscriptionCredentials":            {Owner: "channel", UserCallers: []string{}, SystemCallers: []string{"relay", "channel"}},
	"/api.channel.v1.ChannelService/ClaimSubscriptionCredentialRefresh":      {Owner: "channel", UserCallers: []string{}, SystemCallers: []string{"relay", "channel"}},
	"/api.channel.v1.ChannelService/UpdateSubscriptionAccount":               {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/DeleteSubscriptionAccount":               {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/ChangeSubscriptionAccountStatus":         {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/RecordAccountQuotaSnapshot":              {Owner: "channel", UserCallers: []string{}, SystemCallers: []string{"relay", "channel"}},
	"/api.channel.v1.ChannelService/RecordSubscriptionAccountQuotaUsage":     {Owner: "channel", UserCallers: []string{}, SystemCallers: []string{"relay", "billing"}},
	"/api.channel.v1.ChannelService/AggregateSubscriptionAccountQuotaEvents": {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/ResetSubscriptionAccountQuota":           {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/GetChannel":                              {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{"relay", "monitor"}},
	"/api.channel.v1.ChannelService/ListAvailableModels":                     {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{"relay"}},
	"/api.channel.v1.ChannelService/ListChannels":                            {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{"monitor"}},
	"/api.channel.v1.ChannelService/CreateChannel":                           {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/UpdateChannel":                           {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/RecordChannelUsage":                      {Owner: "channel", UserCallers: []string{}, SystemCallers: []string{"relay"}},
	"/api.channel.v1.ChannelService/RecordChannelHealth":                     {Owner: "channel", UserCallers: []string{}, SystemCallers: []string{"relay", "monitor"}},
	"/api.channel.v1.ChannelService/RecordSubscriptionAccountHealth":         {Owner: "channel", UserCallers: []string{}, SystemCallers: []string{"relay"}},
	"/api.channel.v1.ChannelService/RecordSubscriptionAccountSlot":           {Owner: "channel", UserCallers: []string{}, SystemCallers: []string{"relay"}},
	"/api.channel.v1.ChannelService/DeleteChannel":                           {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/ChangeChannelStatus":                     {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/ListModels":                              {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/GetModel":                                {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/CreateModel":                             {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/UpdateModel":                             {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/DeleteModel":                             {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/ChangeModelStatus":                       {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/BatchModels":                             {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/ListModelAliases":                        {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/CreateModelAlias":                        {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/DeleteModelAlias":                        {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/ListChannelModelMappings":                {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/UpsertChannelModelMapping":               {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/DeleteChannelModelMapping":               {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/ListSubscriptionModelMappings":           {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/UpsertSubscriptionModelMapping":          {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/DeleteSubscriptionModelMapping":          {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/RecordModelUsage":                        {Owner: "channel", UserCallers: []string{}, SystemCallers: []string{"relay"}},
	"/api.channel.v1.ChannelService/ListModelUsageStats":                     {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/RecordModelHealth":                       {Owner: "channel", UserCallers: []string{}, SystemCallers: []string{"relay"}},
	"/api.channel.v1.ChannelService/ListModelHealth":                         {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/ListModelRoutings":                       {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/UpsertModelRouting":                      {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/DeleteModelRouting":                      {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/CanonicalModelPreflight":                 {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/MergeCanonicalModels":                    {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/ListUnpricedRoutedModels":                {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/ExportModels":                            {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/ImportModels":                            {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/DryRunImportModels":                      {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/RecordUsageSemanticVerdict":              {Owner: "channel", UserCallers: []string{}, SystemCallers: []string{"relay"}},
	"/api.channel.v1.ChannelService/ResolveUsageSemanticBlock":               {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.channel.v1.ChannelService/ListUsageSemanticBlocks":                 {Owner: "channel", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.billing.v1.BillingService/GetSubscriptionUsage":                    {Owner: "billing", UserCallers: []string{"admin"}, SystemCallers: []string{"identity"}},
	"/api.billing.v1.BillingService/ExecuteSubscriptionCommerce":             {Owner: "billing", UserCallers: []string{"admin"}, SystemCallers: []string{"identity"}},
	"/api.billing.v1.BillingService/GetRoutingBillingPolicy":                 {Owner: "billing", UserCallers: []string{"admin"}, SystemCallers: []string{"channel"}},
	"/api.billing.v1.BillingService/PublishRoutingBillingPolicy":             {Owner: "billing", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.billing.v1.BillingService/GetRoutingGroupPrice":                    {Owner: "billing", UserCallers: []string{"admin"}, SystemCallers: []string{"relay", "channel"}},
	"/api.billing.v1.BillingService/SetUserRoutingPrice":                     {Owner: "billing", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.billing.v1.BillingService/ClearUserRoutingPrice":                   {Owner: "billing", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.billing.v1.BillingService/CheckRoutingSettlement":                  {Owner: "billing", UserCallers: []string{"admin"}, SystemCallers: []string{"relay"}},
	"/api.billing.v1.BillingService/GetRoutingCapabilities":                  {Owner: "billing", UserCallers: []string{"admin"}, SystemCallers: []string{"relay"}},
	"/api.billing.v1.BillingService/ReserveQuota":                            {Owner: "billing", UserCallers: []string{}, SystemCallers: []string{"relay"}},
	"/api.billing.v1.BillingService/ListRequestAttempts":                     {Owner: "billing", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.billing.v1.BillingService/CommitQuota":                             {Owner: "billing", UserCallers: []string{}, SystemCallers: []string{"relay"}},
	"/api.billing.v1.BillingService/ReleaseQuota":                            {Owner: "billing", UserCallers: []string{}, SystemCallers: []string{"relay"}},
	"/api.billing.v1.BillingService/GetAccountSnapshot":                      {Owner: "billing", UserCallers: []string{"admin"}, SystemCallers: []string{"relay", "identity"}},
	"/api.billing.v1.BillingService/TopUpQuota":                              {Owner: "billing", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.billing.v1.BillingService/PurchaseSubscription":                    {Owner: "billing", UserCallers: []string{"admin"}, SystemCallers: []string{"identity"}},
	"/api.billing.v1.BillingService/CreateRedeemCode":                        {Owner: "billing", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.billing.v1.BillingService/CreateRedeemCodesBatch":                  {Owner: "billing", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.billing.v1.BillingService/RedeemCode":                              {Owner: "billing", UserCallers: []string{"admin"}, SystemCallers: []string{"identity"}},
	"/api.billing.v1.BillingService/GetRedeemCode":                           {Owner: "billing", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.billing.v1.BillingService/ListRedeemCodes":                         {Owner: "billing", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.billing.v1.BillingService/SearchRedeemCodes":                       {Owner: "billing", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.billing.v1.BillingService/UpdateRedeemCode":                        {Owner: "billing", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.billing.v1.BillingService/DeleteRedeemCode":                        {Owner: "billing", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.billing.v1.BillingService/ListLedger":                              {Owner: "billing", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.billing.v1.BillingService/GetLedgerEntry":                          {Owner: "billing", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.billing.v1.BillingService/BatchGetAccountSnapshots":                {Owner: "billing", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.billing.v1.BillingService/CreatePaymentOrder":                      {Owner: "billing", UserCallers: []string{"admin"}, SystemCallers: []string{"identity"}},
	"/api.billing.v1.BillingService/GetPaymentOrderByTradeNo":                {Owner: "billing", UserCallers: []string{"admin"}, SystemCallers: []string{"identity"}},
	"/api.billing.v1.BillingService/MarkPaymentOrderPaid":                    {Owner: "billing", UserCallers: []string{}, SystemCallers: []string{"identity"}},
	"/api.billing.v1.BillingService/MarkPaymentOrderAssetIssued":             {Owner: "billing", UserCallers: []string{}, SystemCallers: []string{"identity"}},
	"/api.billing.v1.BillingService/UnmarkPaymentOrderAssetIssued":           {Owner: "billing", UserCallers: []string{}, SystemCallers: []string{"identity"}},
	"/api.billing.v1.BillingService/ListPaymentOrders":                       {Owner: "billing", UserCallers: []string{"admin"}, SystemCallers: []string{"identity"}},
	"/api.billing.v1.BillingService/RefundPaymentOrder":                      {Owner: "billing", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.billing.v1.BillingService/SubscriptionOperationReport":             {Owner: "billing", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.billing.v1.BillingService/ListReconciliationRuns":                  {Owner: "billing", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.billing.v1.BillingService/GetReconciliationRun":                    {Owner: "billing", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.billing.v1.BillingService/AggregateLedgerByDate":                   {Owner: "billing", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.billing.v1.BillingService/AggregateUsage":                          {Owner: "billing", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.config.v1.ConfigService/GetConfig":                                 {Owner: "config", UserCallers: []string{"admin"}, SystemCallers: []string{"relay", "identity", "billing", "channel", "notify"}},
	"/api.config.v1.ConfigService/ListConfigs":                               {Owner: "config", UserCallers: []string{"admin"}, SystemCallers: []string{"relay", "identity", "billing", "channel", "notify"}},
	"/api.config.v1.ConfigService/SetConfig":                                 {Owner: "config", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.config.v1.ConfigService/DeleteConfig":                              {Owner: "config", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.log.v1.LogService/GetLog":                                          {Owner: "log", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.log.v1.LogService/ListLogs":                                        {Owner: "log", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.log.v1.LogService/IngestLog":                                       {Owner: "log", UserCallers: []string{}, SystemCallers: []string{"relay", "billing", "identity", "channel"}},
	"/api.monitor.v1.MonitorService/SaveHealthCheck":                         {Owner: "monitor", UserCallers: []string{}, SystemCallers: []string{"monitor"}},
	"/api.monitor.v1.MonitorService/ListHealthChecks":                        {Owner: "monitor", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.monitor.v1.MonitorService/GetLatestHealthCheck":                    {Owner: "monitor", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.monitor.v1.MonitorService/CreateAlertRule":                         {Owner: "monitor", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.monitor.v1.MonitorService/GetAlertRule":                            {Owner: "monitor", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.monitor.v1.MonitorService/ListAlertRules":                          {Owner: "monitor", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.monitor.v1.MonitorService/UpdateAlertRule":                         {Owner: "monitor", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.monitor.v1.MonitorService/DeleteAlertRule":                         {Owner: "monitor", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.notify.v1.NotifyService/CreateNotification":                        {Owner: "notify", UserCallers: []string{}, SystemCallers: []string{"billing", "channel", "monitor"}},
	"/api.notify.v1.NotifyService/GetNotification":                           {Owner: "notify", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.notify.v1.NotifyService/ListNotifications":                         {Owner: "notify", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.notify.v1.NotifyService/UpdateNotificationStatus":                  {Owner: "notify", UserCallers: []string{}, SystemCallers: []string{"notify"}},
	"/api.identity.v1.IAMService/ListResources":                              {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/ListPermissions":                            {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/GetPermission":                              {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/CreatePermission":                           {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/UpdatePermission":                           {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/SetPermissionStatus":                        {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/ArchivePermission":                          {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/GetPermissionReferences":                    {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/ListRoles":                                  {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/GetRole":                                    {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/CreateRole":                                 {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/UpdateRole":                                 {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/CopyRole":                                   {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/SetRoleStatus":                              {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/ArchiveRole":                                {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/GetRoleReferences":                          {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/ListRoleMembers":                            {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/GetRolePermissions":                         {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/UpdateRolePermissions":                      {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/UpdateRoleInheritance":                      {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/PreviewRoleChange":                          {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/GetUserRoles":                               {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/AssignUserRole":                             {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/RevokeUserRole":                             {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/BatchAssignUserRoles":                       {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/PreviewUserRoleChange":                      {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/GetSessionAuthorization":                    {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/GetSessionRoles":                            {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/ActivateSessionRoles":                       {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/RevokeOwnSession":                           {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/RevokeUserSessions":                         {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/ListUserSessions":                           {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/ListDelegations":                            {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/CreateDelegation":                           {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/UpdateDelegation":                           {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/RevokeDelegation":                           {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/ListRoleConstraints":                        {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/CreateRoleConstraint":                       {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/UpdateRoleConstraint":                       {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/DeleteRoleConstraint":                       {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/ListMenuItems":                              {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/CreateMenuItem":                             {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/UpdateMenuItem":                             {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/ArchiveMenuItem":                            {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/CheckAuthorization":                         {Owner: "identity", UserCallers: []string{"admin", "identity", "channel", "billing", "log", "config", "monitor", "notify"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/GetUserEffectivePermissions":                {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/ExplainAuthorization":                       {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/SimulateAuthorizationChange":                {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/ListAuthorizationAuditEvents":               {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/GetAuthorizationAuditEvent":                 {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/ExportAuthorizationAuditEvents":             {Owner: "identity", UserCallers: []string{"admin"}, SystemCallers: []string{}},
	"/api.identity.v1.IAMService/RescueRootCredential":                       {Owner: "identity", UserCallers: []string{}, SystemCallers: []string{"rescue"}},
	"/api.admin.v1.IAMAdminService/ListUserSessions":                         {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/ListResources":                            {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/ListPermissions":                          {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/GetPermission":                            {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/CreatePermission":                         {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/UpdatePermission":                         {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/SetPermissionStatus":                      {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/ArchivePermission":                        {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/GetPermissionReferences":                  {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/ListRoles":                                {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/GetRole":                                  {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/CreateRole":                               {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/UpdateRole":                               {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/CopyRole":                                 {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/SetRoleStatus":                            {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/ArchiveRole":                              {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/GetRoleReferences":                        {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/ListRoleMembers":                          {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/GetRolePermissions":                       {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/UpdateRolePermissions":                    {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/UpdateRoleInheritance":                    {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/PreviewRoleChange":                        {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/GetUserRoles":                             {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/AssignUserRole":                           {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/RevokeUserRole":                           {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/BatchAssignUserRoles":                     {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/PreviewUserRoleChange":                    {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/GetSessionAuthorization":                  {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/GetSessionRoles":                          {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/ActivateSessionRoles":                     {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/RevokeOwnSession":                         {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/RevokeUserSessions":                       {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/ListDelegations":                          {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/CreateDelegation":                         {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/UpdateDelegation":                         {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/RevokeDelegation":                         {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/ListRoleConstraints":                      {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/CreateRoleConstraint":                     {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/UpdateRoleConstraint":                     {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/DeleteRoleConstraint":                     {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/ListMenuItems":                            {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/CreateMenuItem":                           {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/UpdateMenuItem":                           {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/ArchiveMenuItem":                          {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/CheckAuthorization":                       {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/GetUserEffectivePermissions":              {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/ExplainAuthorization":                     {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/SimulateAuthorizationChange":              {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/ListAuthorizationAuditEvents":             {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/GetAuthorizationAuditEvent":               {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.admin.v1.IAMAdminService/ExportAuthorizationAuditEvents":           {Owner: "admin", UserCallers: []string{}, SystemCallers: []string{}},
	"/api.relay.v1.RelayService/ChatCompletion":                              {Owner: "relay", UserCallers: []string{"admin"}},
	"/api.relay.v1.RelayService/ListModels":                                  {Owner: "relay", UserCallers: []string{"admin"}},
	"/api.identity.v1.IAMService/GetResourceAuthorization":                   {Owner: "identity", SystemCallers: []string{"admin", "identity", "channel", "billing", "config", "log", "monitor", "notify"}},
}
