server:
  http:
    addr: 0.0.0.0:8003
  grpc:
    addr: 0.0.0.0:9003
data:
  database:
    driver: mysql
    source: ${DATABASE_DSN:-root:password@tcp(127.0.0.1:3306)/oneapi}
  redis:
    addr: ${REDIS_ADDR:-127.0.0.1:6379}

