// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/go-kratos/kratos/v3"
	"github.com/go-kratos/kratos/v3/registry"
	"github.com/google/wire"
	"micro-one-api/app/identity/internal/biz"
	"micro-one-api/app/identity/internal/data"
	"micro-one-api/app/identity/internal/server"
	"micro-one-api/app/identity/internal/service"
	"micro-one-api/platform/audit"
	registry2 "micro-one-api/platform/registry"
	"micro-one-api/platform/routingclient"
	"micro-one-api/platform/security"
	"os"
)

// Injectors from wire.go:

func InitApp(confPath string) (*kratos.App, func(), error) {
	config, err := loadConfig(confPath)
	if err != nil {
		return nil, nil, err
	}
	repository, err := newRepo(config)
	if err != nil {
		return nil, nil, err
	}
	auditor := newAuditAuditor()
	identityUsecase := biz.NewIdentityUsecase(repository, auditor)
	identityService := service.NewIdentityService(identityUsecase)
	providerRegistry := setupOAuth(config)
	mainRegistrarResult := provideRegistrar(config)
	app, cleanup := newApp(config, repository, identityUsecase, identityService, providerRegistry, mainRegistrarResult)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

var ProviderSet = wire.NewSet(
	newRepo,
	newAuditAuditor, biz.NewIdentityUsecase, service.NewIdentityService, server.NewGRPCServer, provideRegistrar, wire.Bind(new(biz.IdentityRepo), new(*data.Repository)),
)

// newAuditAuditor provides the audit sink for identity-service login/logout
// events. Unconditionally enabled; events go to the structured application log.
func newAuditAuditor() *audit.Auditor {
	return audit.NewAuditor(true)
}

func newRepo(cfg *Config) (*data.Repository, error) {

	if !usesExplicitIdentityMemoryRepository(cfg) {
		if err := requireIdentitySecrets(); err != nil {
			return nil, err
		}
	}
	repo, err := data.NewRepositoryFromEnv(cfg.Bootstrap.Data.Database.Driver, cfg.Bootstrap.Data.Database.Source, cfg.Bootstrap.Data.Database.Schema)
	if err != nil {
		return nil, err
	}
	if biz.RoutingV2Enabled() {
		if err := repo.CheckRoutingSchema(context.Background()); err != nil {
			return nil, err
		}
	}
	return repo, nil
}

type registrarResult struct {
	Registrar registry.Registrar
}

func provideRegistrar(cfg *Config) registrarResult {
	registrar, err := registry2.NewRegistrar(cfg.Registry())
	if err != nil {
		return registrarResult{}
	}
	return registrarResult{Registrar: registrar}
}

func newApp(
	cfg *Config,
	repo *data.Repository,
	uc *biz.IdentityUsecase,
	svc *service.IdentityService,
	oauthRegistry *oauth.ProviderRegistry,
	reg registrarResult,
) (*kratos.App, func()) {
	closeRouting := func() {}
	closeOutbox := func() {}
	if biz.RoutingV2Enabled() {
		reader, cleanup, err := routingclient.Dial(os.Getenv("CHANNEL_GRPC_ENDPOINT"))
		if err != nil {
			panic(err)
		}
		uc.SetRoutingGroupReader(reader)
		closeOutbox = repo.StartRoutingOutbox()
		closeRouting = cleanup
	}
	bootstrapAdmin(uc)
	grpcSrv := server.NewGRPCServer(cfg.Bootstrap.Server.Grpc.Addr, svc)
	billingClient, billingConn, _ := newBillingClient(cfg)
	httpSrv := server.NewHTTPServerWithRegistrationPolicy(
		cfg.Bootstrap.Server.Http.Addr, uc, oauthRegistry,
		registrationPolicyFromConfig(cfg), billingClient,
	)
	opts := []kratos.Option{kratos.Name("identity-service"), kratos.Server(grpcSrv, httpSrv)}
	if reg.Registrar != nil {
		opts = append(opts, kratos.Registrar(reg.Registrar))
	}
	app := kratos.New(opts...)
	return app, func() {
		closeOutbox()
		closeRouting()
		if billingConn != nil {
			billingConn.Close()
		}
	}
}
