// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/go-kratos/kratos/v3"
	"github.com/go-kratos/kratos/v3/registry"
	"github.com/go-kratos/kratos/v3/transport/http"
	"github.com/google/wire"
	"micro-one-api/api/billing/v1"
	"micro-one-api/api/channel/v1"
	"micro-one-api/api/identity/v1"
	"micro-one-api/app/admin/internal/biz"
	"micro-one-api/app/admin/internal/server"
	"micro-one-api/app/admin/internal/service"
	"micro-one-api/platform/audit"
	registry2 "micro-one-api/platform/registry"
	"time"
)

// Injectors from wire.go:

func InitApp(confPath string) (*kratos.App, func(), error) {
	config, err := loadConfig(confPath)
	if err != nil {
		return nil, nil, err
	}
	mainClientsResult, err := newClients(config)
	if err != nil {
		return nil, nil, err
	}
	mainSubscriptionResult := newSubscriptionUsecases(config)
	billingServiceClient := provideBillingClient(mainClientsResult)
	identityServiceClient := provideIdentityClient(mainClientsResult)
	channelServiceClient := provideChannelClient(mainClientsResult)
	mainSystemOptionsResult := newSystemOptionsRepo(config)
	systemOptionsUsecase := newSystemOptionsUsecase(mainSystemOptionsResult)
	adminService := service.NewAdminService(billingServiceClient, identityServiceClient, channelServiceClient, systemOptionsUsecase)
	auditor := newAuditAuditor()
	mainRegistrarResult := provideRegistrar(config)
	app, cleanup := newApp(config, mainClientsResult, mainSubscriptionResult, adminService, auditor, mainRegistrarResult)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

var ProviderSet = wire.NewSet(
	newClients,
	newSystemOptionsRepo,
	newSystemOptionsUsecase,
	newSubscriptionUsecases,
	provideIdentityClient,
	provideChannelClient,
	provideBillingClient,
	newAuditAuditor, service.NewAdminService, provideRegistrar,
)

// newAuditAuditor provides the audit sink for admin-api sensitive operations
// (refunds, balance changes). Unconditionally enabled.
func newAuditAuditor() *audit.Auditor {
	return audit.NewAuditor(true)
}

func provideIdentityClient(c *clientsResult) identityv1.IdentityServiceClient {
	return c.identityClient
}

func provideChannelClient(c *clientsResult) channelv1.ChannelServiceClient { return c.channelClient }

func provideBillingClient(c *clientsResult) billingv1.BillingServiceClient { return c.billingClient }

func newSystemOptionsUsecase(r systemOptionsResult) *biz.SystemOptionsUsecase {
	if r.Repo == nil {
		return nil
	}
	return biz.NewSystemOptionsUsecase(r.Repo)
}

type registrarResult struct {
	Registrar registry.Registrar
}

func provideRegistrar(cfg *Config) registrarResult {
	registrar, err := registry2.NewRegistrar(cfg.Registry())
	if err != nil {
		return registrarResult{}
	}
	return registrarResult{Registrar: registrar}
}

func newApp(
	cfg *Config,
	clients *clientsResult,
	sub subscriptionResult,
	svc *service.AdminService,
	auditor *audit.Auditor,
	reg registrarResult,
) (*kratos.App, func()) {

	if sub.SubUc != nil {
		planUc := sub.PlanUc
		svc.SetSubscriptionUsecases(sub.SubUc, sub.GroupUc, planUc)
	}

	workerCtx, cancelWorker := context.WithCancel(context.Background())
	worker := service.NewUnpricedRoutedMetricWorker(svc, 60*time.Second)
	go worker.Run(workerCtx)

	grpcSrv := newGRPCServer(cfg, svc)

	// Build HTTP server with nil-safety checks.
	var httpSrv *http.Server
	if cfg.Bootstrap != nil && cfg.Bootstrap.Server != nil && cfg.Bootstrap.Server.Http != nil &&
		cfg.Bootstrap.Clients != nil && cfg.Bootstrap.Clients.Identity != nil {
		httpSrv = server.NewHTTPServer(cfg.Bootstrap.Server.Http.Addr, svc, auditor, cfg.Bootstrap.Clients.Identity.HttpEndpoint, cfg.Bootstrap.Server.Http.WebRoot)
	} else {
		httpSrv = server.NewHTTPServer("", svc, auditor, "", "")
	}

	opts := []kratos.Option{kratos.Name("admin-api"), kratos.Server(grpcSrv, httpSrv)}
	if reg.Registrar != nil {
		opts = append(opts, kratos.Registrar(reg.Registrar))
	}
	app := kratos.New(opts...)

	startSignalHandler(appSignalStopper{app})

	return app, func() {
		cancelWorker()
		if clients != nil {
			clients.identityConn.Close()
			clients.channelConn.Close()
			clients.billingConn.Close()
		}
	}
}
